### ISSUE TITLE
Release and versioning strategy

### ISSUE THREAD

**Issue by rvagg** [nodejs/readable-stream#101]
Here's the background of how readable-stream has been working until now:

* joyent/node 0.10.x releases get pulled in to the v0.10 branch with the `./build/build.js` script, if tests pass it gets published as 1.0.x (i.e. where "x" matches the 0.10 release). 
* joyent/node 0.11.x releases get pulled in to the master branch with the `./build/build.js` script, if tests pass it gets published as 1.1.x (i.e. where "x" matches the 0.11 release). 
* Only 1.0.x releases get tagged as `latest`, all 1.1.x releases are tagged as `1.1` - this means that `npm install readable-stream` defaults to the "stable" streams2 version and if you want the "unstable" streams3 you have to explicitly fetch it from 1.1.x. (Note: I follow a similar strategy with through2)

This wasn't meant to be a scalable process and was going to change when 0.12 was released anyway: 1.1.x would become `latest` and perhaps even become 1.2.x to match the versioning. Streams3 would become default and streams2 would slowly slip away.

Now that io.js has been released and there is increasing skepticism that 0.12 will ever be released it's probably time to just say that streams3 should be the new default and streams2 along with the 1.0.x series should be deprecated. But there are some questions to be answered:

* What versioning scheme should be adopted? Perhaps we should just bump to 3.0.0 and start fresh!
* How do we manage "releases" in conjunction with merging code upstream to the io.js codebase
* How do we deal with changes in joyent/node streams and can we exert any influence over that? Perhaps we can do a similar upstreaming there, except we have the 0.10 conflict to deal with. The fact that the API in 0.10 is still apparently in flux (e.g. https://github.com/joyent/node/pull/7856) really bothers me and I'd like to see if we can put a stop to that.

**Comment by rvagg** [comment]
Also, I'll continue to advocate that people use readable-stream over core streams, as per [this rant](http://r.va.gg/2014/06/why-i-dont-use-nodes-core-stream-module.html) into the future, it'll still make sense post-io.js, so getting a release process here is just as important as an upstream merge strategy IMO.

**Comment by substack** [comment]
Would it be possible to rip readable-stream out of iojs and bring it back out as a vendored dependency, like how libuv is managed and how readable-stream started out? This might hurt node <-> iojs interop but it is a good direction for the project overall and will mean that readable-stream can focus on stream-specific issues with versioning separate from node core.

**Comment by mikeal** [comment]
+1 on 3.0.0 versioning to properly describe the "version of streams" ;)

**Comment by rvagg** [comment]
@substack that's exactly what we're doing. It was decided early on that all streams code, docs and issues would live here and releases be upstreamed to io.js. The process is just getting underway so if you'd like to be involved I'm sure everyone would appreciate your participation.

**Comment by substack** [comment]
Thanks for the clarification. Separate management will also make pulling in readable-stream from browserify easier and perhaps with this restructuring we won't need shims like https://www.npmjs.com/package/stream-browserify any longer.

**Comment by sonewman** [comment]
> +1 on 3.0.0 versioning to properly describe the "version of streams" ;)

+1 I this this would be a good idea too

**Comment by sonewman** [comment]
potentially we could also back version streams2 to be v2.0.0 as well?

**Comment by vkurchatkin** [comment]
> Would it be possible to rip readable-stream out of iojs and bring it back out as a vendored dependency, like how libuv is managed and how readable-stream started out?

this https://github.com/iojs/io.js/issues/445 kind of gets in the way

**Comment by chrisdickinson** [comment]
Per the WG meeting:

* We're okay with bumping to 3.0.0.
* We'll iterate on versions ourselves and recommend specific releases to the io.js TC.
* We'll take patches from joyent/node where available and applicable.

**Comment by calvinmetcalf** [comment]
settled on just using streams specific semver
