### ISSUE TITLE
util-deprecate missing

### ISSUE THREAD

**Issue by vegar** [nodejs/readable-stream#103]
Our build stopped working this weekend. During gulp tasks the following error is thrown:

```javascript
module.js:340
throw err;
^
Error: Cannot find module 'util-deprecate'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Module.require (module.js:364:17)
at require (module.js:380:17)
at Object.<anonymous> (C:\a\src\WebApiRole\node_modules\gulp-minify-css\node_modules\gulp-util\node_modules\multipipe\node_modules\duplexer2\node_modules\readable-stream\lib\_stream_writable.js:143:8)
´´´

Can this have something to do with the merge of #98 ? As I understand the following lines, all ´util.deprecated´ is replaced with a ´require('util-deprecated')´, but ´util-deprecated´ is not part of ´packages.json´.

**Comment by sonewman** [comment]
This could be an issue. As far as I know though we have not released this change. Are you using this directly from github?

**Comment by sonewman** [comment]
I have raised a PR for this https://github.com/iojs/readable-stream/pull/104

**Comment by vegar** [comment]
We are getting this indirectly from gulp. The dep.graph is something like 
gulp->gulp-util->multipipe->duplexer2->readable-stream.

**Comment by sonewman** [comment]
Oh well that is strange because that wouldn't be installing the current `master`

**Comment by vegar** [comment]
Strange indeed... 

I'll do some more research and see if I can uncover what's happening. 

Mvh,
-Vegar

**Comment by vegar** [comment]
By comparing my colleagues (that gets the error) and mine (which doesn't get the error) node_modules folder after a clean npm install, it's clear that he gets the github source and I get the npmjs.org version.

But why?

I'm trying to compare npm configs and such, but can't see anything that looks related.

**Comment by sonewman** [comment]
That is extremely strange and doesn't make sense. Are you both using the same version of npm?

**Comment by vegar** [comment]
we started out with different versions, but even after updating node and npm, the differenece persists.

**Comment by sonewman** [comment]
Hmm, you did point out a valuable thing though, because the dependency had been missed from the `package.json`

**Comment by vegar** [comment]
(y)
looks like a ´npm cache clear´  on the failing machines might do the trick btw.
