### ISSUE TITLE
Keeping up to date with io.js?

### ISSUE THREAD

**Issue by mhart** [nodejs/readable-stream#116]
As things currently stand, streams in io.js are now ahead of this library – this library now being under the `iojs` GitHub account makes this a bit confusing.

Is there a plan to keep this in sync with io.js? Or just Node?

**Comment by calvinmetcalf** [comment]
see #117

**Comment by calvinmetcalf** [comment]
published

**Comment by mhart** [comment]
Awesome, thanks :+1:
