### ISSUE TITLE
release

### ISSUE THREAD

**Issue by calvinmetcalf** [nodejs/readable-stream#117]
we moved to put out a release at the last meeting, but we haven't actually done it yet.  Do we have a procedure for this?

**Comment by rvagg** [comment]
what is the status of the code in here? does it track io.js? was it agreed to jump to 3.0.0? who should be responsible for releases? I have publish access and could hand it over to someone the WG selects if there is a procedure and plan in place.

**Comment by chrisdickinson** [comment]
It tracks io.js. It was agreed to jump to 3.0.0. Unsure who is responsible for releases.

**Comment by rvagg** [comment]
fine, I can take responsibility for now, I'll do a 3.0.0 with the current codebase now unless someone tells me otherwise

**Comment by rvagg** [comment]
also .. how's the browserify support? do all of the transforms get applied to make it es3-happy or are we ditching that?

**Comment by calvinmetcalf** [comment]
I don't see why we'd ditch that

**Comment by rvagg** [comment]
well if you reverse the flow of code then it would be ditched -- the support came via the transformations that were applied in the build script (like [this one for `Array#forEach()`](https://github.com/iojs/readable-stream/blob/master/build/common-replacements.js#L1-L8), is that still being used to transfer code from io.js to here?

**Comment by calvinmetcalf** [comment]
I didn't think we reversed the flow yet

**Comment by mhart** [comment]
@chrisdickinson when you say it "tracks io.js" what does that mean exactly? This codebase is currently behind where io.js is, for example – so I would've thought a 3.0.0 release would at least reflect where io.js is...?

**Comment by chrisdickinson** [comment]
@mhart There are build scripts that pull in the changes from io.js, but they are still run manually.

**Comment by mhart** [comment]
Ah cool, gotcha.

Well my two cents would be that I'd love that script to be run before the next release, so that we can use the new constructor hotness. But not too fussed.

**Comment by sonewman** [comment]
+1 on discussing this. We should iron out this process for the future.

**Comment by mhart** [comment]
Yo yo, what's the news on this?

**Comment by calvinmetcalf** [comment]
done
