### ISSUE TITLE
[discuss] emit 'end' on process.exit

### ISSUE THREAD

**Issue by missinglink** [nodejs/readable-stream#118]
one little thing that gets me every time is that streams don't necessarily flush when the process exits.

in the case of a lazy readable forgetting to explicitly push `null` or call `end()` then your `_flush` code will never run:

``` javascript
var stream = createStream();
stream.write('a');
```

``` bash
$ node streams.js 
data
```

.. obviously doing it the right way works great:

``` javascript
var stream = createStream();
stream.write('a');
stream.end();
```

``` bash
$ node streams.js 
data
done
```

is this an issue for anyone else or am I the only idiot having this issue?

``` javascript
var stream = createStream();

process.on('exit',function(code){
  code || stream.end();
});

stream.write('a');
```

``` bash
$ node streams.js 
data
done
```
# 

`createStream.js`

``` javascript
var through = require('through2');

var xform = function( chunk, enc, next ){
  console.log('data');
  this.push( chunk );
  next();
};

var flush = function(){
  console.log('done');
};

function createStream(){
  return through.obj( xform, flush );
}

module.exports = createStream;
```

**Comment by sonewman** [comment]
I don't think it's that uncommon. The problem here is education into the usage of Streams.

The thing end could essentially be called at any place in time (same tick, next tick, etc.) so it would not be possible to assume when to call end (or even Readable#push(null))

There is also no feasibly way to keep track of all the streams and end them on process end, that would be asking for a memory leak.

There is already a lot of good streams related documentation and resources.

But I guess the take away is, how can we document this better so it's clear how this works.

**Comment by calvinmetcalf** [comment]
@missinglink fyi the reason we can't just add

```
process.on('exit', function () {
    stream.end();
});
```

is because process is going to exit next tick with no way to stop it, meaning the flush will only work if it's totally synchronous, so as it turns out

```js
process.on('exit',function(code){
  code || stream.end();
});
```
is totally the right thing to be doing if you need to make sure your sync flush event runs.

**Comment by sindresorhus** [comment]
Node.js now has the [`beforeExit`](https://nodejs.org/api/process.html#process_event_beforeexit) event that does allow doing async ops before exiting.

**Comment by calvinmetcalf** [comment]
`process.on('beforeexit',()=> stream.end());` would be something that could help in a lot of code, though it won't help when exit is called explicitly...

**Comment by mafintosh** [comment]
what about the times i dont want my streams to end, ever. i dont think adding more magic to the streams api make it easier to understand.

**Comment by calvinmetcalf** [comment]
oh I wasn't suggesting that we add it, I was saying that it might help certain peoples code

**Comment by mafintosh** [comment]
ah cool, carry on then :)

**Comment by mcollina** [comment]
I think this is not needed anymore. Feel free to reopen if we need to discuss this further.
