### ISSUE TITLE
io.js readable-streams WG meeting #2

### ISSUE THREAD

**Issue by chrisdickinson** [nodejs/readable-stream#120]
Here's a [doodle](http://doodle.com/6sxfq7ycw3fcr9c4) for planning a time (all times PST). I can revise if it doesn't work for folks.

The tentative agenda:
- deprecate stream1#pipe() #114
- Callback for async _read #113
- Proposal: add _flush to Writable streams #112 
- 'continue' event for Readable streams #111
- crypto streams #109 
- Reconciliation Proposal iojs/io.js#978
- Stream not emitting data after pipe/unpipe iojs/io.js#1041

If possible I'd also like to cut a release next week – v3.0.0 – bringing in the changes from io.js.

EDIT:

Link to minutes: https://docs.google.com/document/d/1VYwQi2DT40doiYZQMCJsJMbv-jnjtvjyi653QViMcnc/edit
Link to join: https://plus.google.com/hangouts/_/hoaevent/AP36tYc_Qt7W4-x4RxifhXg_XCgbcZ4eymAe-7Rz4Tvg7pDrdeIicQ

**Comment by chrisdickinson** [comment]
Hah! Forgot to actually link to the doodle :| Updated the issue text with the doodle, but for email users: http://doodle.com/6sxfq7ycw3fcr9c4

**Comment by sonewman** [comment]
Hey :smiley:, Is there any chance we can briefly touch on https://github.com/iojs/io.js/issues/978 if there is time? It would be good to understand where we stand on this.

**Comment by chrisdickinson** [comment]
Sure! Added to the agenda.

**Comment by sonewman** [comment]
Awesome, thanks!

**Comment by chrisdickinson** [comment]
Hey folks! Sorry for letting this one linger for so long. I'm leaning towards 11am PST on Thursday for the time. Are there any objections? We can bump it earlier if need be.

**Comment by calvinmetcalf** [comment]
PST or PDT?

**Comment by sonewman** [comment]
@chrisdickinson, that's fine with me.

**Comment by calvinmetcalf** [comment]
Works as well here (previous comment meant to ask if you meant to say pdt)

**Comment by calvinmetcalf** [comment]
we still on for 45 minutes from now ?

**Comment by chrisdickinson** [comment]
Yep!

**Comment by chrisdickinson** [comment]
Hey all – started the hangout on air. Share links have been sent out, and the link to join is above. PM me on IRC if you can't get in. Thanks!

**Comment by chrisdickinson** [comment]
Hey @iojs/streams – we (myself, @calvinmetcalf and @sonewman) opted to reschedule this meeting to try and get input for these issues. We talked briefly about some impediments to pulling in changes from + exporting changes to io.js core (re: I made spooky, hand-wave-y motions about private modules landing in io.js core.)

Action items in brief:

* I'm going to open another doodle.
* We're going to see about cutting a release after running tests, etc. We may need to loop @rvagg in for this.

**Comment by sonewman** [comment]
Hey! So whats the plan, should we resuscitate this ticket to serve for the next meeting? or create a new one?

**Comment by mscdex** [comment]
What ever became of this meeting? I'm still interested in hearing what people think/have to say about the topics that were going to be discussed.

**Comment by sonewman** [comment]
good question +1
