### ISSUE TITLE
readable.unshift(chunk) not resetting state.reading

### ISSUE THREAD

**Issue by zoubin** [nodejs/readable-stream#126]
I'm wondering why `unshift` does not reset the reading flag. Here is the source code in `readableAddChunk`:
```javascript
if (!addToFront) {
  state.reading = false;
}
```

And it seems weird to me:

```javascript
var rs = new require('stream').Readable({ objectMode: true });

var data = ['Hello, ', 'world!'];
rs._read = function () {
    if (!data.length) {
        this.push(null);
    } else {
        this.unshift(data.pop());
        // push('') is necessary here
        // this.push('');
    }
};

var res = '';
rs.on('data', function (d) {
    res += d;
});
rs.on('end', function () {
    // without push(''), res only contains 'world!'
    console.log(res.length, res);
});
```

Actually, the example given in the [documentation](https://nodejs.org/api/stream.html#stream_example_simpleprotocol_v1_sub_optimal) fails because it does not push('') after unshift.

**Comment by zoubin** [comment]
I think I'd better ask the question in another place.

**Comment by sonewman** [comment]
@zoubin this may be a bug unless i miss understand the purpose of `.unshift()` @iojs/streams are you using streams3?

**Comment by sonewman** [comment]
No this is the right place.

In the code it suggests that unshift should be used when a stream is currently `reading`. 

The reason it does not emit the data is because
```javascript
  // however, if we've ended, then there's no point, and if we're already
  // reading, then it's unnecessary.
  if (state.ended || state.reading) { // READING === false when unshifting
    doRead = false;
    debug('reading or ended', doRead);
  }

  if (doRead) {
    debug('do read');
    state.reading = true;
    state.sync = true;
    // if the length is currently zero, then we *need* a readable event.
    if (state.length === 0)
      state.needReadable = true;
    // call internal read method
    this._read(state.highWaterMark);
    state.sync = false;
  }
```
https://github.com/iojs/readable-stream/blob/master/lib/_stream_readable.js#L342-L359

Basically the problem is that `state.reading = false` only happens if data is being pushed, and it will only trigger a call to `_read()` internally if `state.reading === true`.

The thing about `.unshift()` is that it has a valid use case in the situation where you may be listening to `on('data', () => {})` and want to actually push back some data into the buffer:
```javascript
readable.on('data', function (chunk) {
  var c;
  if (chunk.length <= 10) {
     c = chunk;
  } else {
    writable.write(chunk.slice(0, 11));
    this.unshift(chunk.slice(11));
  }
});
```
But I think it's something worth discussing.

**Comment by sonewman** [comment]
@isaacs addressed this in https://github.com/nodejs/readable-stream/issues/127 it seems the use of unshift is strictly for pushing half processed data back onto the beginning of the stream buffer. So it is only likely to be used in certain specific use cases and therefore the best action is to improve `documentation` in this area.

**Comment by zoubin** [comment]
Thanks! It really helps.

**Comment by varenc** [comment]
Hey @sonewman, fun thing: the code you cited in this old issue just appeared in a Law & Order SVU Episode S27E04! screenshots

<img width="1812" height="1094" alt="Image" src="https://github.com/user-attachments/assets/afdd8eb5-6854-4a13-a5bc-3129f8503942" />

<img width="732" height="326" alt="Image" src="https://github.com/user-attachments/assets/fa897b9b-2f75-4507-b793-2359ba01d462" />

It's originally from [readable-stream](https://github.com/nodejs/readable-stream/tree/d0d888fc86cb30d33ca45f7adad3ac68e7a9afbe/lib/_stream_readable.js) circa 2015 of course, but your quote of it seems to be the most prominent copy I find still online.  So possible that the show creators were citing you/this issue.
