### ISSUE TITLE
No encoding for `unshift` - should there be?

### ISSUE THREAD

**Issue by sonewman** [nodejs/readable-stream#127]
This might be a non issue, I just wanted to raise it as a question really as to if there was any particular reason that we don't set any encoding for data which is added via `unshift`.

```javascript
Readable.prototype.unshift = function(chunk, **no encoding here**) {
  var state = this._readableState;
  // i would assume that rather than explicitly setting the encoding to ""
  // we would allow the second option, unless there is a specific reason
  // which I have missed ??
  return readableAddChunk(this, state, chunk, '', true);
};
```

https://github.com/iojs/readable-stream/blob/master/lib/_stream_readable.js#L145-L149

**Comment by calvinmetcalf** [comment]
Does having an empty string do the same thing as it being undefined?

**Comment by chrisdickinson** [comment]
Before we change unshift, we should probably look into whether anyone's actually using it. For my part, I haven't heard of any usages.

**Comment by sonewman** [comment]
I was really just raising it as an observation for discussion, I'll be honest I don't have any real opinions on it other than that it seemed a little in consistent.

But based on the suggested use case it seems that it would be used for putting slices of data back onto the beginning of the stream buffer after it has been emitted in a `data` (or possibly `readable`) event.

**Comment by sonewman** [comment]
I guess the only thing i did think was that if an encoding had been supplied when the data was added, if the data was then put back onto the beginning of the stream buffer it would not have that associated any more. But I wondered how many people use streams with chunks of data that would consist of different encodings (maybe some weird protocol...). Anyway if we are happy this is a conscious choice then feel free to close and move on :smile:

**Comment by isaacs** [comment]
There is a reason why there's no encoding there.  Think about what it would mean if you specified an encoding on this function which was different than the encoding used by the stream.

```javascript
var r = new ReadableFoo({ encoding: null }) // chunks come out as Buffers
r.push(new Buffer('foo'))
var str = r.read().toString('hex') // not a buffer!
r.push(new Buffer('foo'))
r.unshift(str) // now we've got a hex string in the queue along with Buffers...
```

In order to support an encoding here, any time the encoding differs from the stream's configured encoding, then we'd have to transmute it before putting it back into the stream queue, or else the concat/length/etc stuff would all be fubar.  It gets even weirder if it's utf/ucs, and you get a chunk that splits a surrogate pair!

The pushed chunk **must** be a chunk returned by `stream.read()`, same encoding and everything.  We should fix this with documentation and maybe a run-time assert.

**Comment by sonewman** [comment]
@isaacs thanks for the explanation that was really helpful, I stumbled across this when looking into https://github.com/iojs/readable-stream/issues/126.

The fact that `unshift` is intended to be used as explained now brings clarity to this particular issue. Since `unshift` is more of a utility for managing data flow rather than claiming parity to `Array.prototype.unshift` despite on the face of it doing a similar function.

I not sure how we want to manage something like this but perhaps we can put a `documentation` label on it for the appropriate action.
