### ISSUE TITLE
add error forwarding

### ISSUE THREAD

**Issue by calvinmetcalf** [nodejs/readable-stream#129]
add the ability to forward errors when we pipe, probably want it to be opt in at first, this would be both useful and in line with how whatwg streams work

**Comment by sonewman** [comment]
+1, when we say error forwarding do we mean these errors would propagate up and down the chain?

**Comment by calvinmetcalf** [comment]
Yeah working on a pull to io

**Comment by mikeal** [comment]
Do we still think this is a good idea?

We had planned to do this years ago but since then a lot of work has gone in to how we encapsulate errors, I wonder if this is still a good idea or not.

**Comment by wonderdogone** [comment]
As @calvinmetcalf mentioned this would keep node streams more in "sync" with whatwg streams no? And i think thats a good idea. Maybe a better question would be why would one not want to pass the error along? I suspect it would only increase usability.

**Comment by ivan** [comment]
I don't think think it makes sense to forward `end` but not `error`.  I'm using steams extensively in one project and have 21 calls to my `pipeWithErrors` helper, which is everywhere that I want to pipe something.

**Comment by yoshuawuyts** [comment]
@ivan I'm using [`pump`](https://github.com/mafintosh/pump) to handle errors and close streams for me. It calls a cb with (error) if there was an error in any of the streams.

**Comment by yoshuawuyts** [comment]
Actually it might be a good idea to make `pump`'s behavior an option in `.pipe()`. E.g. something like:
```js
readable.pipe(writable, { chain: true })
```
Not sure if `chain` is the right word, but having a way to knit multiple streams together as if they were one would be super beneficial. Opinions?

**Comment by goloroden** [comment]
@yoshuawuyts I like you idea :-). What about `forwardErrors` as key?

**Comment by yoshuawuyts** [comment]
I think short, memorable names might be better, `forwardErrors` feels a bit verbose.

**Comment by calvinmetcalf** [comment]
so there are [some problems](https://github.com/nodejs/node/pull/1521#issuecomment-96964344) with adding the option.

**Comment by BenoitClaveau** [comment]
+1

**Comment by mcollina** [comment]
I think this is superseded by #283.
