### ISSUE TITLE
Nominate npm releaser(s) for readable-stream

### ISSUE THREAD

**Issue by rvagg** [nodejs/readable-stream#134]
As much as I'd like to be involved I have to be honest about my time availability and I just don't have the bandwidth to grok where this project even is at right now.

So, I'd like @nodejs/streams to nominate an individual (or >1 indiviuals if you have a plan for how that'll work) that should have npm publish rights for this package.

For background purposes, the current situation is like this:

`@latest` tag sticks to the `1.0.x` releases where the `x` matches the Node.js `v0.10.x` version, with the code extracted out of Node.js, passed through the build/ scripts in the `v0.10` branch to make it stand-alone and browserifiable. When you `npm install readable-stream` you get this, which is streams2.

`@1.1` tag (which I don't think it's even possible to publish under with npm now because it doesn't like version-like tags) sticks to the `1.1.x` releases where the `x` matches the Node.js `v0.11.x` version, with the code extracted out of Node.js, passed through the build/scripts on the `master` branch. You have to `npm install readable-stream@1.1` (or a specific version) to get this branch, which is streams3.

We currently have nothing for 0.12 but it may make sense to continue on the `1.1.x` series with those for continuity.

My hope was that we would jump a semver-major (or two) and start tracking io.js because it represents the best state of streams and it should go in `@latest`. How that works exactly is up to you guys.

Have a meeting, get a consensus or something and let me know who should be doing the releases.

**Comment by calvinmetcalf** [comment]
If we were to jump to 2.0.2 that would match current node (i could merge
io-stream back in and publish it as is)

**Comment by mafintosh** [comment]
@calvinmetcalf sounds like a good idea. @chrisdickinson thoughts?

**Comment by dcousens** [comment]
@calvinmetcalf up to the task?

**Comment by calvinmetcalf** [comment]
I'd be honored, I'll open a pull to get [io-stream](https://github.com/calvinmetcalf/io-stream) merged back in

**Comment by calvinmetcalf** [comment]
see #135

**Comment by rvagg** [comment]
going ahead and giving @calvinmetcalf publish rights

@calvinmetcalf: in case you're not doing this as part of your normal workflow already, please make sure you use `npm version <whatever>` to increment versions with `npm config set sign-git-tag=true` with your GPG key available and set up with git. Then we'll continue get signed git tags for each release for readable-stream.

Let us know what happens with versions, I'm still not clear on what the plan is but we'll want to update through2 to match.

**Comment by mafintosh** [comment]
@rvagg @calvinmetcalf :tada:

**Comment by calvinmetcalf** [comment]
excellent, will set up gpg now

**Comment by calvinmetcalf** [comment]
should I publish my key somewhere ?

**Comment by rvagg** [comment]
you can push it to the git repo itself, I can't remember the details but I'm sure google will enlighten

**Comment by calvinmetcalf** [comment]
published, put the key in the readme
