### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by calvinmetcalf** [nodejs/readable-stream#136]
discussion of what our next release should be

- 3.0.0 for the first one of streams 3
- 2.2.1 to match the version of iojs it's from
- 2.0.0 as a semantic major bump from where it is now

**Comment by calvinmetcalf** [comment]
ping @nodejs/streams

**Comment by mafintosh** [comment]
Excited about releasing this! I would just 2.0.0 the next release. Matching the iojs version doesn't seem to add that much benefit IMO since iojs will probably be released a lot more than the stream module.

**Comment by calvinmetcalf** [comment]
went with option 3 and 2.0.0 is published
