### ISSUE TITLE
Stream export missing in 2.0.0

### ISSUE THREAD

**Issue by dougwilson** [nodejs/readable-stream#143]
Hi! It looks like the commit d0d888fc86cb30d33ca45f7adad3ac68e7a9afbe may have accidentally broken the `Stream` export. This is because it's assigning `exports.Stream` first, but then re-assigning the value of `exports` right after, so `exports.Stream` is now missing.

Example
```js
require('readable-stream').Stream // undefined after the above the commit
```

**Comment by calvinmetcalf** [comment]
Woops we probably want to set exports.Stream to be the same as module.exports if we can't import stream

**Comment by dougwilson** [comment]
In this case, importing `stream` works fine, bu the order of the lines are stomping on each other :)

Instead of
```js
(function (){
  try {
    exports.Stream = require('st' + 'ream'); // hack to fix a circular dependency issue when used with browserify
  } catch(_){}
}());
exports = module.exports = require('./lib/_stream_readable.js');
```

they need to be in the other order:

```js
exports = module.exports = require('./lib/_stream_readable.js');
(function (){
  try {
    exports.Stream = require('st' + 'ream'); // hack to fix a circular dependency issue when used with browserify
  } catch(_){}
}());
```

**Comment by calvinmetcalf** [comment]
Yes the other thing is for use in browserify.

**Comment by dougwilson** [comment]
Thank you, 2.0.1 fixes the issue :)
