### ISSUE TITLE
cork()/uncork() and pipe()

### ISSUE THREAD

**Issue by indutny** [nodejs/readable-stream#145]
It would be great if `pipe()` could somehow do `cork()`/`uncork()` to minimize amount of the TCP packets when piping to the `net.Socket`. Does anyone have an idea how to expose this to users? Or how to handle it?

Should we just cork and uncork on next tick as we do in http?

**Comment by calvinmetcalf** [comment]
something like https://github.com/calvinmetcalf/SBS ?

**Comment by indutny** [comment]
Yeah, but with `._writev` call in the end. It is not currently possible to control this.

**Comment by indutny** [comment]
My use case is following (if you are interested). I have a protocol framer (say HTTP2), which is basically a readable stream. It emits frames in chunks (i.e. separate chunk for header, for body, sometimes more), and always does this synchronously (i.o.w. without delay between the chunks).

The owner of the framer pipes it into the socket, and now all of these pushes in framer result in separate TCP packets (especially when using noDelay), but it could potentially be just a single `_writev` call. I can do `.cork()`/`.uncork()` manually, but it will mean that I will need to reimplement `.pipe()` in my code.

**Comment by calvinmetcalf** [comment]
could be an option we could add to pipe

**Comment by indutny** [comment]
Oh, that sounds right! I forgot that `.pipe()` has options.

**Comment by trevnorris** [comment]
Why not auto cork on the initial write and queue a nextTick to uncork? Could be an option on the pipe, but the handling of packets is automated.

**Comment by indutny** [comment]
@trevnorris this is what I want :)

**Comment by calvinmetcalf** [comment]
@indutny nodejs/io.js#2020

**Comment by mcollina** [comment]
Closing now, as the PR has been debated and closed.
