### ISSUE TITLE
`emptying` event

### ISSUE THREAD

**Issue by indutny** [nodejs/readable-stream#148]
After reaching the `highWaterMark` - Writable stream starts returning `false` on `.write()` calls. Same happens on `.push()` calls in Readable stream. However there is no way to figure out or to be notified when there is a headroom for the data to be written.

In other words, it would be great to have a notification when the user read from the stream and it is buffered contents size is smaller or equal than `lowWaterMark`. So far I have came up only with `emptying` name, but maybe someone has better suggestions.

cc @calvinmetcalf

**Comment by indutny** [comment]
Here is how I do it in spdy-transport at the moment: https://github.com/indutny/spdy-transport/blob/master/lib/spdy-transport/stream.js#L140

**Comment by mafintosh** [comment]
Isn't `_read` currently called when the buffer is below hwm?

**Comment by indutny** [comment]
Hm... looks like so. Yeah, you are right.

Thank you!
