### ISSUE TITLE
Next WG Meeting?

### ISSUE THREAD

**Issue by sonewman** [nodejs/readable-stream#149]
It feel like some of our motivation may have lost speed. That might just be me talking...

But it would be good to regroup and talk some of the pressing outstanding issues through.

So how about another WG Meeting?

**Comment by calvinmetcalf** [comment]
Just got back from vacation, so now would be down for one any time

**Comment by dcousens** [comment]
I'm not part of the WG,  but I'd be happy to help.

**Comment by calvinmetcalf** [comment]
@dcousens there is really nothing preventing you from becoming part of the WG, this stuff is very much a do-ocracy

**Comment by wonderdogone** [comment]
Looks like things have slowed here? Still doing and upcoming meeting?

**Comment by yunong** [comment]
@chrisdickinson Is this the repository of record for the WG? If not where is it?

**Comment by calvinmetcalf** [comment]
https://github.com/nodejs/readable-stream/tree/master/doc/wg-meetings

**Comment by mcollina** [comment]
I think we should do a meeting to kickstart some discussions and improvements. Who wants to organize and prepare an agenda?

**Comment by calvinmetcalf** [comment]
I started an agenda in #183 if others want to add to it

**Comment by yoshuawuyts** [comment]
I'm interested int his, can I join this meeting?

**Comment by calvinmetcalf** [comment]
yes
