### ISSUE TITLE
RangeError in maybeReadMore

### ISSUE THREAD

**Issue by agulowaty** [nodejs/readable-stream#157]
Hello all,

I desperately need a help in understanding stack trace with errors:
```
RangeError: Invalid array length
    at maybeReadMore (_stream_readable.js:439:13)
    at readableAddChunk (_stream_readable.js:167:7)
    at Readable.push (_stream_readable.js:127:10)
    at read (tls.js:521:12)
    at Readable.read (_stream_readable.js:340:10)
    at flow (_stream_readable.js:607:52)
    at _stream_readable.js:578:7
---------------------------------------------
    at Readable.pipe (_stream_readable.js:577:13)
    at pipe (tls.js:1406:18)
    at exports.connect (tls.js:1352:19)
    at Agent.createConnection (https.js:79:14)
    at Agent.createSocket (http.js:1293:16)
    at Agent.addRequest (http.js:1269:23)
    at new ClientRequest (http.js:1416:16)
    at exports.request (https.js:123:10)
---------------------------------------------
    at Request.init (PROJECT_DIR\node_modules\request\request.js:676:3)
    at proto.init (PROJECT_DIR\node_modules\request-debug\index.js:76:43)
    at new Request (PROJECT_DIR\node_modules\request\request.js:283:8)
    at request (PROJECT_DIR\node_modules\request\index.js:50:10)
    at request.post (PROJECT_DIR\node_modules\request\index.js:80:27)
```

Node version: v0.10.31
request: ~2.51.0
I'm not sure if this kind of exception is caused by some issue in _stream_readable or rather incorrect usage of stream library by request.js. 

Thanks for help in advance.

**Comment by calvinmetcalf** [comment]
so that is an error you get when you try to create an Array without an integer length (aka a float), since from what I can tell [_stream_readable in node v0.10.31](https://github.com/joyent/node/blob/7fabdc23d843cb705d2d0739e7bbdaaf50aa3292/lib/_stream_readable.js) doesn't create an array, i'd suspect the issue is with request or your client code.

**Comment by agulowaty** [comment]
I'm not an node stack traces expert, could you tell me how it's possible that 
'''
at maybeReadMore (_stream_readable.js:439:13)
'''
is on top and and the exception does not match with the respective method ?

**Comment by agulowaty** [comment]
Maybe problem is caused by wrong assignment to `.length` property (like assigning `undefined`) somewhere in the lib ? I've seen a lot of such error-prone operations in node libraries. I'm not saying this is problem with readable-stream lib, maybe request module holds some state or what not, but I really need to track down this problem.

**Comment by calvinmetcalf** [comment]
what are you doing in your code that causes this to happen?

**Comment by agulowaty** [comment]
Long story short:
In our project we got several libraries to interact with REST APIs, so we encapsulated that logic in node modules. At the top of each module we got at least:

```
 var request = require('request'), q = require('q');
```

Then we usually perform things like:
```
exports.getSomething = function (options) {
  var defer = q.defer();
  request(options, function() { ...});
  return defer.promise;
};

exports.anotherApiCall = function(options) { }

```

Usually we're firing many calls from the same library.
I'm wondering, maybe there is some odd state in the `readable_stream` or `request` modules that causes this stuff to happen.

**Comment by calvinmetcalf** [comment]
are you able to figure out which of the calls to request (looks like a call to request.post) that is causing this?

**Comment by agulowaty** [comment]
Nothing special here, this is how options looks like:
`request.post(options, callback);`
```
{ 
    url: 'https://XXXXXXXX/administrators',
    rejectUnauthorized: false,
    headers:{ 
       Authorization: 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9',
      'User-Agent': 'TA node request',
       Accept: 'application/json, */*',
      'Content-Type': 'application/json' 
    },
    body: '{"timeZone":"europeBelgrade","readOnly":false,"email":"XXXXXXXXXXXXXXXXX","password":"XXXXXXXXXX","phone":"+12XXXXXXXXX","username":"XXXXXXXXXXXXXX,"language":"en_GB"}' 

}
```

But I'm not suspecting that call, rather some leftovers from previous calls, before that call I'm firing several GETs and handling them in q.defer() callbacks like this:

```
administrators.getAll()
.then(function (result) {
  return createNew();
 })
.then(function (result) {
  done();
});
```

**Comment by agulowaty** [comment]
Problem resolved after switching Promise library from q to bluebird and adapting request module with bluebird Promise.promisify(). Thanks for your attention.
