### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by id0Sch** [nodejs/readable-stream#167]
Hi,
im install newrelic and i get the following error:
```
npm WARN unmet dependency /home/ubuntu/code/node_modules/newrelic/node_modules/concat-stream/node_modules/readable-stream requires inherits@'~2.0.1' but will load
npm WARN unmet dependency undefined,
npm WARN unmet dependency which is version undefined
```
I would like your advice on how to resolve this issue
thanks.

**Comment by calvinmetcalf** [comment]
try `rm -rf node_modules && npm install`

**Comment by id0Sch** [comment]
I did that multiple times,
the only that worked for me is to go into /home/ubuntu/code/node_modules/newrelic/node_modules/concat-stream/node_modules/readable-stream dir and run npm install from there.
the thing is, the initial npm install runs on jenkins instance that resets between each build, and the issue started today.

**Comment by yoshuawuyts** [comment]
@id0Sch what version of `node` and `npm` are you running?

**Comment by id0Sch** [comment]
as a result from apt-get install nodejs + npm im getting:
nodejs v0.10.25
npm 1.3.10

does that make any sense?

**Comment by calvinmetcalf** [comment]
can you post the package.json file from the `/home/ubuntu/code/node_modules/newrelic/node_modules/concat-stream/node_modules/readable-stream` folder ?

**Comment by id0Sch** [comment]
```
{
  "_args": [
    [
      "readable-stream@~2.0.0",
      "/private/var/folders/39/58wtn5sd2b5_1zwl_4t_1dw00000gp/T/tmp-50068gPr7bQc03vHX/node-newrelic/node_modules/concat-stream"
    ]
  ],
  "_from": "readable-stream@>=2.0.0 <2.1.0",
  "_id": "readable-stream@2.0.3",
  "_inCache": true,
  "_location": "/concat-stream/readable-stream",
  "_nodeVersion": "4.1.1",
  "_npmUser": {
    "email": "calvin.metcalf@gmail.com",
    "name": "cwmma"
  },
  "_npmVersion": "2.14.4",
  "_phantomChildren": {},
  "_requested": {
    "name": "readable-stream",
    "raw": "readable-stream@~2.0.0",
    "rawSpec": "~2.0.0",
    "scope": null,
    "spec": ">=2.0.0 <2.1.0",
    "type": "range"
  },
  "_requiredBy": [
    "/concat-stream"
  ],
  "_resolved": "https://registry.npmjs.org/readable-stream/-/readable-stream-2.0.3.tgz",
  "_shasum": "4ab16b2aba452374b542a3f4f528634b9b45bb5a",
  "_shrinkwrap": null,
  "_spec": "readable-stream@~2.0.0",
  "_where": "/private/var/folders/39/58wtn5sd2b5_1zwl_4t_1dw00000gp/T/tmp-50068gPr7bQc03vHX/node-newrelic/node_modules/concat-stream",
  "browser": {
    "util": false
  },
  "bugs": {
    "url": "https://github.com/nodejs/readable-stream/issues"
  },
  "dependencies": {
    "core-util-is": "~1.0.0",
    "inherits": "~2.0.1",
    "isarray": "0.0.1",
    "process-nextick-args": "~1.0.0",
    "string_decoder": "~0.10.x",
    "util-deprecate": "~1.0.1"
  },
  "description": "Streams3, a user-land copy of the stream library from iojs v2.x",
  "devDependencies": {
    "tap": "~0.2.6",
    "tape": "~4.0.0",
    "zuul": "~3.0.0"
  },
  "directories": {},
  "dist": {
    "shasum": "4ab16b2aba452374b542a3f4f528634b9b45bb5a",
    "tarball": "http://registry.npmjs.org/readable-stream/-/readable-stream-2.0.3.tgz"
  },
  "gitHead": "58099551e1ea7d99f8d13495740c5ae3f5d98053",
  "homepage": "https://github.com/nodejs/readable-stream#readme",
  "installable": true,
  "keywords": [
    "pipe",
    "readable",
    "stream"
  ],
  "license": "MIT",
  "main": "readable.js",
  "maintainers": [
    {
      "name": "isaacs",
      "email": "isaacs@npmjs.com"
    },
    {
      "name": "tootallnate",
      "email": "nathan@tootallnate.net"
    },
    {
      "name": "rvagg",
      "email": "rod@vagg.org"
    },
    {
      "name": "cwmma",
      "email": "calvin.metcalf@gmail.com"
    }
  ],
  "name": "readable-stream",
  "optionalDependencies": {},
  "repository": {
    "type": "git",
    "url": "git://github.com/nodejs/readable-stream.git"
  },
  "scripts": {
    "browser": "npm run write-zuul && zuul -- test/browser.js",
    "test": "tap test/parallel/*.js",
    "write-zuul": "printf \"ui: tape\nbrowsers:\n  - name: $BROWSER_NAME\n    version: $BROWSER_VERSION\n\">.zuul.yml"
  },
  "version": "2.0.3"
}
```

**Comment by calvinmetcalf** [comment]
try running `npm install -g npm` to upgrade npm

if that doesn't work then I suspect you might have a caching issue going on as you are not getting the most recent version of readable stream and I only get that kind of error you are getting when I'm installing a single module somewhere I already have other's installed.

**Comment by id0Sch** [comment]
yeah I suspect a caching issue as well, but it would be weird as the same exact build succeeded this morning w/o any other change.
any ways, upgrading npm did not do the trick as I still get the same error

thanks for your help!

**Comment by calvinmetcalf** [comment]
this is likely not an issue with this project but with npm or possibly jenkins.  One last thing you can try is `npm cache clean`

**Comment by id0Sch** [comment]
I changed newrelics' version to be a fixed version in the package.json and it seemed to solve the problem.
thanks guys for your help!
the issue may is resolved, at least at my end

**Comment by lucyl** [comment]
Having exactly the same issue. Looking at the logs the last successful build was using 
newrelic@1.22.2 node_modules/newrelic
and after that all failing builds have 
newrelic@1.23.0 node_modules/newrelic.

**Comment by calvinmetcalf** [comment]
@lucyl set newrelic to 1.22.2 seamed to fix it for @id0Sch.  This is almost definitely an issue with newrelic, npm, or whatever you are using to build it
