### ISSUE TITLE
noob question, source.pipe(T).write(applies to sink :( )

### ISSUE THREAD

**Issue by maboiteaspam** [nodejs/readable-stream#174]
Hi,

Just some questions that i don t know where to post, feel free to close if irrelevant,

In this,

```js
through2()
 .pipe(through2(function (c,e,n){
      n(null,c)
  })).pipe(through2(function (c,e,n){
      n(null,c)
  })).pipe(through2(function (c,e,n){
    n(null,c)
  })).write('does not matter')
```

Would it not be more usable that __this__ `write()` applies to the `source` rather than the `sink` ?

Even though it should break some software engineering concepts, agreed, 
I still want to ask this, does it make sense to write the stream by the last transform in such demonstration ?

**Comment by calvinmetcalf** [comment]
- You can have multiple sources piping to the same thing so this is a bit more complicated in practice 
- what if you wanted to insert data in the middle of a pipe stream, like skip the first couple, this would prevent that. 

Thanks for the idea, I'm not sure it would make things more clear just trade one confusing case for another.

**Comment by maboiteaspam** [comment]
guess my usage of streams is weeeaakkk to see those things. Will read that https://github.com/calvinmetcalf/streams-a-love-story
thanks for the slides !
