### ISSUE TITLE
Drop IE < 9 support

### ISSUE THREAD

**Issue by shinnn** [nodejs/readable-stream#175]
Since Microsoft has halted to support Internet Explorer < 9, we can remove a lot of workarounds for browser compatibility. For example,

* Use [`Array.isArray`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray) directly instead of [`isarray`](https://github.com/juliangruber/isarray) module.
* Remove [`Object.keys`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Object/keys) [polyfill](https://github.com/nodejs/readable-stream/blob/b6810590821e2082d5b79e3e0d08d3d090ebc353/build/common-replacements.js#L29-L36).
* Remove [`Array.prototype.forEach`](https://developer.mozilla.org/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) [polyfill](https://github.com/nodejs/readable-stream/blob/b6810590821e2082d5b79e3e0d08d3d090ebc353/build/common-replacements.js#L1-L13).

This introduces a breaking change and requires a major version bump.

**Comment by rvagg** [comment]
Can you outline the benefits of doing this? It's not clear to me that the win is big enough to justify the possible pain. Just because Microsoft is dropping support doesn't mean people will stop using it.

**Comment by kgryte** [comment]
I would argue against making this change. Even if the argument is performance, the perf gains for using "native" methods will be minimal, at best.

**Comment by calvinmetcalf** [comment]
not sure we can even drop these pollyfills even if we drop old IE support due to the long tail of shitty android browsers. Closing.
