### ISSUE TITLE
April 2016 working group meeting 

### ISSUE THREAD

**Issue by calvinmetcalf** [nodejs/readable-stream#183]
tentative plan for first or second week of april

Agenda (to be added to):

- more frequent meetings
- proactively add moar tests (to prevent issues like  https://github.com/nodejs/node/issues/5820)
- destroy method https://github.com/nodejs/node/issues/4401
- flush type thing for writable streams (aka my end pull) https://github.com/nodejs/node/issues/2314
- reconcile behavior of `write(null)` between `Writable` and `Trasnform` when `objectMode: true` https://github.com/nodejs/node/issues/5711 https://github.com/nodejs/node/pull/5729
- Remove the use of `_events` #184 https://github.com/nodejs/node/pull/5127 https://github.com/nodejs/node/pull/6032
- error handling
- readable-stream status
- status of whatwg streams
- address issues from https://github.com/nodejs/readable-stream/issues/181

**Comment by mcollina** [comment]
Sorry for disappearing. Let's plan this again for next week (4/4) or the week after that (4/10)?

**Comment by calvinmetcalf** [comment]
doodle link http://doodle.com/poll/5rn4evy4vp54pw63

cc @nodejs/streams @chrisdickinson @domenic @mcollina @mafintosh @ sonewman @rvagg @yoshuawuyts @jmm @stevemao @shinnn @ofrobots @TriAnMan @indutny

**Comment by yunong** [comment]
I'd like to join this meeting.

**Comment by calvinmetcalf** [comment]
everyone's invited

![invited](https://cloud.githubusercontent.com/assets/1128607/14121346/10166b3a-f5c5-11e5-9558-a79ab0907154.jpg)

**Comment by yoshuawuyts** [comment]
:sparkles: yay! :sparkles: Looks like living in Australia isn't ideal, but... all filled in!

I quite like the initial agenda. Perhaps something to add: talk on how to turn streams WG meetings from annually into something a bit more frequent - monthly? bi-monthly?

Oh, perhaps also talk about docs? If we've got time that is, it looks like it's a pretty packed agenda already hah.

Looking forward to talking to you all (if the doodle schedule allows it)! :grin:

**Comment by mcollina** [comment]
Added one more entry.

This look like a long meeting. Should we prioritize a bit into three categories: how we work going forward, stuff we need to handle asap, and breaking changes?

**Comment by calvinmetcalf** [comment]
ok sounds good, reordered

**Comment by sonewman** [comment]
I feel pretty out of touch with the currently issues, so if there are any other open issues from from the main nodejs repo it would be good to link them here.

**Comment by mcollina** [comment]
@sonewman I added some more context. Let me know if this clearer now, or point out what is missing.

**Comment by calvinmetcalf** [comment]
ok guys I'm tentatively scheduling for Monday the 11th and 1pm est ([local time](http://www.timeanddate.com/worldclock/fixedtime.html?msg=Streams+Working+Group&iso=20160411T13&p1=43)) sorry @yoshuawuyts we will try to make the next one Australian accessible

**Comment by mcollina** [comment]
@calvinmetcalf are we using hangouts? Should we make that public? Anybody knows how the CTC handles this kind of stuff?

**Comment by calvinmetcalf** [comment]
we used a hangout last time and that seemed to work, the ctc uses uberconference from what I can tell but I have no experience with that.

**Comment by sonewman** [comment]
@mcollina awesome, thanks. @calvinmetcalf sounds good, i'll try my best to make it!

**Comment by calvinmetcalf** [comment]
ok I'll plan on making a hangout and posting a link to it on monday unless anyone has objections

**Comment by mcollina** [comment]
Go ahead
Il giorno ven 8 apr 2016 alle 18:11 Calvin Metcalf <notifications@github.com>
ha scritto:

**Comment by calvinmetcalf** [comment]
ok should be able to join the event via [this link](https://plus.google.com/events/c4c0vdtb2disvka636srsb1s350?authkey=CLC1l8ulhs__5QE) at 1.

**Comment by calvinmetcalf** [comment]
agenda/notes: https://docs.google.com/document/d/1f4GuVR8EfBN3YhPSm1R-x2VOY1WMb7XJ2aBMW86-hk0/edit?usp=sharing

**Comment by mscdex** [comment]
Any chance #111 could be brought up at this or the next meeting?

**Comment by calvinmetcalf** [comment]
next meeting definitely sorry about that
