### ISSUE TITLE
Fails with composition of two writable streams and lot of data

### ISSUE THREAD

**Issue by anton-makarov** [nodejs/readable-stream#187]
This example will fail in node v0.10.37 with "Maximum call stack size exceeded" error.

``` js
var WritableStream = require('readable-stream').Writable,
	util = require('util');


var InternalStream = function() {
	WritableStream.call(this);
};
util.inherits(InternalStream, WritableStream);

InternalStream.prototype._write = function(chunk, encoding, callback) {
	callback();
};

var internalStream = new InternalStream();



var ExternalStream = function(writable) {
	this._writable = writable;
	WritableStream.call(this);
};
util.inherits(ExternalStream, WritableStream);

ExternalStream.prototype._write = function(chunk, encoding, callback) {
	this._writable.write(chunk, encoding, callback);
};



var externalStream = new ExternalStream(internalStream);

for (var i = 0; i < 2000; i++) {
	externalStream.write(i.toString());
}
```

This code makes sense since [duplexer2](https://github.com/deoxxa/duplexer2) uses readable-stream.

**Comment by calvinmetcalf** [comment]
what version of readable streams ?

**Comment by calvinmetcalf** [comment]
this doesn't cause an error in the current version of readable stream, I seem to remember this being an issue in an older version of streams

**Comment by anton-makarov** [comment]
Readable stream version 2.0.5. Yep, it breaks on node v0.10.37, but works fine on newer versions (0.12 and 5.5)

**Comment by okv** [comment]
nodejs 0.10.42 readable stream 2.0.5 - same error

**Comment by calvinmetcalf** [comment]
hm key will be fixing it in a way that doesn't cause a slowdown in other versions

**Comment by mcollina** [comment]
I fear this might be a duplexer2 issue rather than a readable-stream one.
The "right" way to do what duplexer2 is doing is how @mafintosh [duplexify](http://npm.im/duplexify) does it: https://github.com/mafintosh/duplexify/blob/master/index.js#L194-L202 vs https://github.com/deoxxa/duplexer2/blob/master/index.js#L56-L58. The way duplexer2 handles it is not really respecting backpressure.

BTW, I'm culprit of the same problem: https://github.com/mcollina/reduplexer/blob/master/index.js#L147.

**Comment by calvinmetcalf** [comment]
merged in #188

**Comment by okv** [comment]
Great news, code above now works with readable stream 2.0.6.
But unfortunately original [duplexer2 issue](https://github.com/deoxxa/duplexer2/issues/23) still exists - example from that issue (when duplexer2 uses readable stream 2.0.6) fails with same error.

**Comment by mcollina** [comment]
I think duplexer2 is not really respecting the backpressure contract, but I might be wrong.
Would you mind writing another example that use only this library so we can easily fix it?

**Comment by okv** [comment]
Currently I don't have any idea for another example.
