### ISSUE TITLE
Check for setImmediate support missing for 0.8

### ISSUE THREAD

**Issue by iarna** [nodejs/readable-stream#190]
Specifically, the decision to use `process.nextTick` is determined by this check:

https://github.com/nodejs/readable-stream/blob/4102464299a5a5ba94307776863614042c9ece35/build/files.js#L154
```
var asyncWrite = !process.browser && ['v0.10' , 'v0.9.'].indexOf(process.version.slice(0, 5)) > -1 ? setImmediate : processNextTick;
```

I would very much like to see this include `v0.8.` in the list because, for instance, `npm` still needs to support it.  (Though I would hasten to add that `npm` doesn't currently make use of the sync functions where this is at play. But shipping with a version of `readable-stream` that isn't entirely compatible with all of our supported versions makes me nervous just the same.)

Alternatively (and maybe better) do a capability check instead of a version check, eg:

```
var asyncWrite = !process.browser && global && global.setImmediate ? setImmediate : processNextTick;
```

**Comment by calvinmetcalf** [comment]
The bug isn't present in 0.8 that's why we don't swap out process.nextTick, we support (and test against) 0.8 as well

**Comment by iarna** [comment]
OH! I totally misread the ` ['v0.10' , 'v0.9.'].indexOf` and was thinking of it as having inverted logic. It only uses `setImmediate` on 0.9 & 0.10. =D 

Never mind, that's obviously fine then.
