### ISSUE TITLE
Support on Microsoft Edge

### ISSUE THREAD

**Issue by seriousme** [nodejs/readable-stream#193]
Hi,

I noticed that Microsoft Edge is missing on the Saucelabs diagram, Saucelabs supports Edge since a few months now.

The saucelabs configurator shows it as:

caps = {browserName: 'MicrosoftEdge'};
caps['platform'] = 'Windows 10';
caps['version'] = '13.10586';

Cheers,
Hans

**Comment by calvinmetcalf** [comment]
Ok i can try again, I tried a couple months back but it wasn't working yet

**Comment by calvinmetcalf** [comment]
done

**Comment by seriousme** [comment]
Great :-)
