### ISSUE TITLE
May working group meeting

### ISSUE THREAD

**Issue by calvinmetcalf** [nodejs/readable-stream#196]
- continue event #111
- tests update
- readable-streams progress
- whatwg streams update whatwg/streams#435

**Comment by mcollina** [comment]
Ping, doodle?

**Comment by calvinmetcalf** [comment]
doodle: http://doodle.com/poll/6h5vz2ab24z4q7hb

**Comment by jennabelle** [comment]
When do we find out when the next meeting for Streams API is? cc'd @jasnell

**Comment by calvinmetcalf** [comment]
ping @nodejs/streams anyone else able to fill out the doodle ?

**Comment by calvinmetcalf** [comment]
@jennabelle probably soon

**Comment by calvinmetcalf** [comment]
ok streams meeting will be scheduled for Wednesday the 18th at 10am est ([local](http://www.timeanddate.com/worldclock/fixedtime.html?msg=Streams+Working+Group+May+Meeting&iso=20160518T10&p1=43&ah=1)) sorry @chrisdickinson would love for you to be there but I promised to make this one viewable for Australians

**Comment by mcollina** [comment]
Folks, I've just realized I couldn't be there, or at best I need to leave at 16:30 CEST :/

**Comment by calvinmetcalf** [comment]
we can try to be quick, there should be too much

**Comment by jennabelle** [comment]
do we usually have a google invite for this?

**Comment by calvinmetcalf** [comment]
I will post one here before hand

**Comment by jennabelle** [comment]
@calvinmetcalf is this still happening tomorrow? I have it on my calendar and want to make sure I receive the meeting link

**Comment by calvinmetcalf** [comment]
yes, before the meeting I will create a hangout and post it here

**Comment by calvinmetcalf** [comment]
heres the viewing link, https://plus.google.com/events/c3grf2c4lmetjh2r31tuv7ei5i4 I'll have the join link in an hour or so

**Comment by calvinmetcalf** [comment]
https://hangouts.google.com/call/jlcq3dwejnhprm6bjoi2ovhaaae

**Comment by calvinmetcalf** [comment]
posted the link you can use to join

**Comment by calvinmetcalf** [comment]
if that doesn't work speak up

**Comment by mcollina** [comment]
we should also talk a bit about https://github.com/nodejs/node/pull/6773/.
