### ISSUE TITLE
depreciate 1.0.x and 1.1.x branch

### ISSUE THREAD

**Issue by calvinmetcalf** [nodejs/readable-stream#201]
newer versions _should_ be 100% backwards compatible with older versions and we should be able to test that thanks to the new flags

Pros:
- old version are not going to be getting bug fixes
- will cause bloat in browserify 
- probably slower

Cons:
- they still work
- current npm depreciation messages are super annoying and not very helpful because they don't tell you what libs require the deprecated libs (or required the lib which required the lib) Though we could include in the message that `npm ls readable-stream@~1.0.0` will tell them the path.
- depreciation messages tend to be seen by people who can't do anything about it

**Comment by mcollina** [comment]
I'm 👎 on doing this now. I'm ok to deprecate both when 0.10 (or maybe even 0.12) exits LTS (October and December 2016). Ideally we should follow the same cycle here.

**Comment by calvinmetcalf** [comment]
so by that reasoning we should be publishing updates to those branches as
well based on updates to 0.10 and 0.12

**Comment by rvagg** [comment]
> so by that reasoning we should be publishing updates to those branches as well based on updates to 0.10 and 0.12

That would be ideal, although I'm not sure there have been any actual updates to streams on 0.10 and 0.12 have there?

**Comment by calvinmetcalf** [comment]
we'd need to backport some of the fixes I made to the master branch to the 1.1.x and 1.0.x branches if we ever had to update them

**Comment by mcollina** [comment]
So, the big question is: what if modules using readable-stream 1 do not work anymore on node 6 (or 7?). How this module is versioned, and how many versions we support (given the current members) it is something that is probably worth discussing in the wg meeting, and maybe even with the LTS team.
October and December seems pretty close as deadlines, and it does not seem we need to anything to get there. However this is a topic is worth discussing.

BTW, I'm ok for deprecating everything before 2. It's just that a policy it is needed: if the policy requires more work, it is highly possible that we might need a lot of help (we already do, BTW).

**Comment by mcollina** [comment]
Deprecating means we do not maintain that anymore, but that will require maintenance on the dependents, to actually update to the new module. I'm ok in causing disruption because we are stretched really thin. In the ideal world we will keep those around until 0.10 and 0.12 are gone from support.
