### ISSUE TITLE
Reduce package size

### ISSUE THREAD

**Issue by sindresorhus** [nodejs/readable-stream#205]
From https://github.com/nodejs/readable-stream/pull/197#discussion_r61090554.

Having to download 2 MB extra makes this module unusable for most smaller modules.

Would be nice to find a way to not have to include those huge dependencies.

**Comment by calvinmetcalf** [comment]
is this an actual problem when used with npm3 ?

**Comment by sindresorhus** [comment]
I'm assuming you're referring to the default deduping. That's only beneficial if it can actually dedupe the dependencies. Many of these dependencies are not that common.

```
├─┬ inline-process-browser@2.0.1
│ ├─┬ falafel@1.2.0
│ │ ├── acorn@1.2.2
│ │ ├── foreach@2.0.5
│ │ ├── isarray@0.0.1
│ │ └── object-keys@1.0.9
│ └─┬ through2@0.6.5
│   ├─┬ readable-stream@1.0.34
│   │ ├── core-util-is@1.0.2
│   │ ├── inherits@2.0.1
│   │ └── string_decoder@0.10.31
│   └── xtend@4.0.1
└─┬ unreachable-branch-transform@0.5.1
  ├── esmangle-evaluator@1.0.0
  └─┬ recast@0.11.5
    ├── ast-types@0.8.16
    ├── esprima@2.7.2
    ├── private@0.1.6
    └── source-map@0.5.5
```

It actually manages to include no more than two JavaScript parsers.

**Comment by calvinmetcalf** [comment]
I meant that it would only ever bring those in once ever, we can switch it to use the same try catch thing that we do already for importing streams when available.
