### ISSUE TITLE
2.1.3 release breaking upstream dependents. Not a patch release?

### ISSUE THREAD

**Issue by jayfresh** [nodejs/readable-stream#210]
Hi,

I noticed that the release earlier today of 2.1.3 coincides with a new problem I have, installing `gulp-imagemin` version 2.3.0, which relies on dependencies that eventually rely on `readable-stream`. This may only be a problem for node v0.12.2 and npm v2.7.4, but all I have to go on is that fresh vms successfully installed `gulp-imagemin` 11 hours ago, and stopped doing so 5 hours ago.

The 2.1.3 release was over 60 files and yet is a patch release from 2.1.2. I wondered if there is any possibility of unpublishing this patch release on npm and promoting it to a major release, since the changes don't seem backwards-compatible, at least from my point of view. `imagemin` relies on "^2.0.0" for example.

Thanks,

Jonathan

**Comment by mafintosh** [comment]
Do you have any idea what broke?

**Comment by mcollina** [comment]
This has been released because it was thought to be backwards compatible (patch-level). Maybe it is not true, but we need to know.

Maybe we should retire the current release and work a bit more on it? But we need to know what we broke.

**Comment by calvinmetcalf** [comment]
The 60 files were mainly test files the only prod files are the ones in lib

**Comment by calvinmetcalf** [comment]
In what way does it not work?

**Comment by jayfresh** [comment]
Hi, sorry not to have posted the error log - it was eventually throwing an error when trying to require `process-nextick-args`. However, as of today it's not a problem any more - clean vms are building fine. Maybe it was an npm caching issue...

**Comment by calvinmetcalf** [comment]
weird, especially as we didn't add that dep in this update, glad it sorted itself out
