### ISSUE TITLE
npm build contains 6.5MB of temp files in hidden .nyc_output folder

### ISSUE THREAD

**Issue by vorg** [nodejs/readable-stream#211]
<img width="584" alt="screen shot 2016-05-19 at 11 36 10" src="https://cloud.githubusercontent.com/assets/171001/15390830/e7a3aa8c-1db5-11e6-8dc8-b4bb1713f34c.png">

**Comment by vorg** [comment]
Somehow it also doesn't dedupe with npm install on node 5.1.3 and i have 22 instances of readable-stream@2.1.3 in my project resulting in 60MB of temp .json files.

**Comment by vorg** [comment]
In my project i have both readable-stream@1.x.x and new readable-stream@2.1.3 so npm dedupes only the first one resulting in remaining 22 copies of 2.x.x and 60MB of temp files.

**Comment by mcollina** [comment]
I don't see how this is a bug of readable-stream and not npm itself. Have you tried updating npm?

**Comment by calvinmetcalf** [comment]
this is the footgun of .npmignore files,, these files were in the
.gitignore only

**Comment by yoshuawuyts** [comment]
I thought [`.npmignore` only added rules to `.gitignore`](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package).

>  If you want to include something that is excluded by your .gitignore file, you can create an empty .npmignore file to override it.

**Comment by calvinmetcalf** [comment]
nope .npmignore *replaces* your .gitignore

**Comment by calvinmetcalf** [comment]
anyway I'm on a plane right now which seems to block git so I can push up a patch when I land and get to my hotel

**Comment by calvinmetcalf** [comment]
fixed
