### ISSUE TITLE
serialport is looking at conforming to streams2+

### ISSUE THREAD

**Issue by chrisdickinson** [nodejs/readable-stream#216]
@reconbot, a maintainer of node-serialport, has expressed interest in conforming [more closely to the streams interface](https://github.com/EmergingTechnologyAdvisors/node-serialport/issues/832). I took a look at the [serialport stream](https://github.com/EmergingTechnologyAdvisors/node-serialport/blob/master/lib/serialport.js) and it looked _pretty close_ to the streams3 interface already, and [commented about the differences](https://github.com/EmergingTechnologyAdvisors/node-serialport/issues/832#issuecomment-222344067).

Could @nodejs/streams take a look & check my assertions there?

**Comment by calvinmetcalf** [comment]
Yup can take a look this week

**Comment by mcollina** [comment]
I think we can close this, feel free to reopen.
