### ISSUE TITLE
port 6.2.2

### ISSUE THREAD

**Issue by mcollina** [nodejs/readable-stream#220]
In order to fix https://github.com/nodejs/LTS/issues/112 we should get 6.2.2 in. 

@calvinmetcalf maybe you should document the process you are following for doing these releases so we might share the burden ;).

**Comment by calvinmetcalf** [comment]
oh the process is easy, just cd into build run npm install if you havn't and then run node build.js x.x.x

the hard part is figuring out why it fails and editing the crazy nest of regexes
