### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by mcollina** [nodejs/readable-stream#221]
I think `readable-stream` currently does not follow semver with Node, i.e. a minor in `readable-stream` is a major in node (more or less). I think at least one change marked as "breaking" slipped in in the 2.x line. 

Would you mind if we move the versioning of this in line to the one of Node.js? How would you do it?

**Comment by mafintosh** [comment]
i think this module should only be versioned on whats happening in this module. if there is a breaking streams change we bump major. what we really need to do to fix this is change the flow of changes so that node core pulls in from readdable-stream and not the other way around.

**Comment by mcollina** [comment]
> i think this module should only be versioned on whats happening in this module. if there is a breaking streams change we bump major

We would need to write some tools to help with tracking the changes before release. Maybe we already have them from the release team.

> what we really need to do to fix this is change the flow of changes so that node core pulls in from readdable-stream and not the other way around.

Really, really 👍 . How do we make this happen?

**Comment by mafintosh** [comment]
@mcollina i forgot to mention that i agree 100% with you that this is a problem currently. 

First step would be to get @nodejs/streams to agree that this is something we need to do. I think we should have a call ASAP to discuss this. Making core pull from readable-stream would also get rid of the annoying build step and compilation we have to do now.

**Comment by yoshuawuyts** [comment]
@mcollina perhaps https://github.com/nodejs/citgm might help to find real-world cases of streams breakage? It's def already being run on the main node repo

**Comment by mafintosh** [comment]
@yoshuawuyts there has been a couple of breaking changes added to streams recently that we in fact know were breaking. the problem lies in remember that when we release a new build of this module.

**Comment by mcollina** [comment]
This is also relevant somehow: https://github.com/nodejs/node/issues/7629.
