### ISSUE TITLE
July working group meeting

### ISSUE THREAD

**Issue by mafintosh** [nodejs/readable-stream#222]
Agenda:

https://github.com/nodejs/node/issues/7629
https://github.com/nodejs/readable-stream/issues/221

**Comment by mafintosh** [comment]
Is there a standard doodle we can copy for figuring out when people can join or something? /cc @calvinmetcalf

**Comment by calvinmetcalf** [comment]
I mean you can copy the last one

**Comment by TheAlphaNerd** [comment]
I'm interested in joining

**Comment by mcollina** [comment]
Anytime in CEST hours works for me.
Ok on Monday 25th on the PST timezone as well (I'll be at NodeSummit).

**Comment by mcollina** [comment]
Here is a doodle for next week: http://doodle.com/poll/484retvrwegvw4pk.

**Comment by mafintosh** [comment]
@mcollina thanks a bunch for setting that up

**Comment by calvinmetcalf** [comment]
yes, thank you, I've been pretty busy of late (and fyi I can actually make all of those I just didn't select ones that are inconvenient for me to make)

**Comment by mcollina** [comment]
Let's close this on Monday.

**Comment by yoshuawuyts** [comment]
I'll be flying to Lisbon at some point next week, but not quite sure when so till I know I'm available like all the time :sparkles:

**Comment by mcollina** [comment]
@TheAlphaNerd @addaleax would you like to join? Which are you preferences?

I would pick Tuesday at 17:00 or 19:00 CEST, if it's ok for everybody.

**Comment by TheAlphaNerd** [comment]
19:00 CEST works for me

**Comment by yoshuawuyts** [comment]
aye works for me, fingers crossed the airport has wifi hah

**Comment by addaleax** [comment]
19:00 works for me too

**Comment by mcollina** [comment]
let's call it at tuesday at 19:00 CEST.

@calvinmetcalf how did you setup the hangouts last time?

**Comment by mcollina** [comment]
Here is the link to join:

https://hangouts.google.com/call/gndqrr3th5etfggmjmb5svbwoue

**Comment by mcollina** [comment]
Here is the link to watch and partecipate: https://plus.google.com/events/civ6j7an5omttn06cpk8hpfm1no

**Comment by mcollina** [comment]
It was just @addaleax, @yoshuawuyts and me :).
Let's reschedule.

**Comment by TheAlphaNerd** [comment]
Sorry, had another call run really long :smile:

**Comment by calvinmetcalf** [comment]
Yeah sorry didn't realize this week

**Comment by mcollina** [comment]
When do you want to reschedule? :)
