### ISSUE TITLE
endless hate debugging readable-stream

### ISSUE THREAD

**Issue by pps83** [nodejs/readable-stream#228]
Not that I'm trying to debug `readable-stream`, but I'm trying to step-through the code with debugger and it's pure irritation with lines like this:

`if (Buffer.isBuffer(chunk)) encoding = 'buffer';else if (!encoding) encoding = state.defaultEncoding;
`
or like that:
`if (state.ended) writeAfterEnd(this, cb);else if (validChunk(this, state, chunk, cb)) {
`
Perhaps it was inherited from older version of node maybe? If I step through regular node then I don't see this kind of debugger unfriendly code.

**Comment by calvinmetcalf** [comment]
nope this is an issue with babel which we use to transform various es6 idioms and it makes some...bizarre white space choices

**Comment by yoshuawuyts** [comment]
`{ compact: false }` might be useful here http://stackoverflow.com/questions/29576341/what-does-the-code-generator-has-deoptimised-the-styling-of-some-file-as-it-e - was dealing with something similar for one of my own packages earlier today

**Comment by pps83** [comment]
I was referring to [this code](https://github.com/nodejs/readable-stream/blob/master/lib/_stream_writable.js#L231). Is it generated by something?
Another point: I think many debuggers either support debugging es6 directly or support stepping through map files (for example, with visual studio you step through typescript directly even though it's compiled to js). So, if these come from es6 source, perhaps it can be done so that in debugger you'd see original src code?

**Comment by mcollina** [comment]
The problem with map files is that we also do some regexp replacement from the stuff that is in core.

An easier option might be passing the code through `standard --fix`.

**Comment by calvinmetcalf** [comment]
@yoshuawuyts that only applies if the file is bigger then like 100k

@pps83 yes babel and in theory you are right it we could do some sort of source map but there is not a great story when it comes to including those in dependencies.  

at the end of the day this is not actually an impediment to read or understand the code as much as it just is mildly irritating due to strangeness as all it is is branch bodies that don't have braces not having a trailing newline

**Comment by mcollina** [comment]
I think the original question was answered. Feel free to reopen if needed.
