### ISSUE TITLE
Add a repository description

### ISSUE THREAD

**Issue by IonicaBizau** [nodejs/readable-stream#229]
...also a website if any. 📝 

![screen shot 2016-09-01 at 14 49 10](https://cloud.githubusercontent.com/assets/2864371/18166337/4ace5586-7053-11e6-9b3d-8cfed59c3e75.png)

**Comment by calvinmetcalf** [comment]
@rvagg or @Fishrock123 do you have access to be able to do that?

**Comment by addaleax** [comment]
Any suggestions? “Node-core streams for userland” + link to https://nodejs.org/api/stream.html? (I would have access, too.)

**Comment by calvinmetcalf** [comment]
yes that sounds great

**Comment by addaleax** [comment]
I’ve added that for now, but I guess it doesn’t hurt to hear what others think? :)

**Comment by mcollina** [comment]
Solved.
