### ISSUE TITLE
WG meeting October 2016

### ISSUE THREAD

**Issue by mcollina** [nodejs/readable-stream#235]
Hi @nodejs/streams,

I propose the week between the 24th and the 28th for running our wg meeting.

Agenda:
- Versioning strategy #234 
- isArray dep #238/ #234 
- When are we going to drop support for Node v0.10 and v0.12?
- `destroy(err)` in node.js v8 as part of the stream standard cc @mafintosh 
- Status of WHATWG streams cc @TheAlphaNerd 
- support for 'flush" in Writable for node.js v8: nodejs/node#2314
- vendor `readable-stream` in core. 
- testing effort on `_readableState`  and `_writableState` cc @mcollina https://github.com/nodejs/node/issues/8644
- streams4 aka end method, destroy, and error propagation 
- doc size #240

cc @TheAlphaNerd @addaleax @mafintosh @calvinmetcalf @bengl @chrisdickinson @yoshuawuyts

If you are ok with this I will send out a doodle.

**Comment by calvinmetcalf** [comment]
I can do the 26th and latter

**Comment by yoshuawuyts** [comment]
yup, works for me

**Comment by mafintosh** [comment]
same

**Comment by TheAlphaNerd** [comment]
I'm on the road Oct 14 - Nov 1. I'll try to make it work whenever you pick

**Comment by mscdex** [comment]
Would it be possible to discuss #111 yet?

**Comment by calvinmetcalf** [comment]
@mcollina we have a date ?

**Comment by mcollina** [comment]
Sorry, nodeconf.eu happened.
I'll fire up a doodle now.

**Comment by mcollina** [comment]
Here is the doodle: http://doodle.com/poll/w2wt6yn4xrprwggz.

My bad if this was late :(.

**Comment by mcollina** [comment]
@mscdex @yoshuawuyts @TheAlphaNerd @addaleax ^^

**Comment by calvinmetcalf** [comment]
its ok I just got back from a holiday in russia

**Comment by mcollina** [comment]
I'll call it for Monday 31st at 1pm CEST.

**Comment by mafintosh** [comment]
@mcollina 👍

**Comment by calvinmetcalf** [comment]
ok I totally didn't realize those times were cest but I should be able to make it though, I may be a smidge tardy

**Comment by mcollina** [comment]
@calvinmetcalf do you want to move it to a later time? I picked 17:00 because it was the latest _you_ were free.

**Comment by calvinmetcalf** [comment]
I thought you picked 13:00 cest? which is 7am edt right?

**Comment by mcollina** [comment]
17:00 CEST, 12:00 EDT.

I can send you a calendar invite if you prefer.

**Comment by mafintosh** [comment]
So its 17 CEST now instead?

**Comment by mcollina** [comment]
oooh, I've selected the right time on the doodle, and completely mistyped here. Today I'm sloppy 😅

**Comment by calvinmetcalf** [comment]
ok that I can make easily

**Comment by addaleax** [comment]
17:00 CEST should work for me too :)

(I am a bit confused/curious though… are there any countries in Europe which won’t be back on CET after sunday?)

**Comment by mafintosh** [comment]
@addaleax good point! @mcollina post a UTC time so we don't mess this up haha

**Comment by mcollina** [comment]
OK. I'm definitely not up to the task 😂😭😱. I can call 16:00 UTC on Monday 31st, but.... feel free to step in and organize this.

**Comment by mafintosh** [comment]
@mcollina it isn't your fault timezones are hard :) 16:00 UTC it is. thanks for taking the time to organise a new meeting

**Comment by mafintosh** [comment]
Turns out @yoshuawuyts and I already have a meeting at the same time. Anyway we can move this forward a couple of hours? Or move it to Tuesday?

**Comment by addaleax** [comment]
Tuesday should work just as well

**Comment by mcollina** [comment]
I'm ok moving it one hour (or two), later. What time?

**Comment by mafintosh** [comment]
Tuesday same time?

**Comment by mcollina** [comment]
Wednesday same time, 16:00 UTC.

Start a new doodle 😂
Il giorno sab 29 ott 2016 alle 01:13 Mathias Buus <notifications@github.com>
ha scritto:

**Comment by sonewman** [comment]
I can do then... Sorry late arrival.

**Comment by calvinmetcalf** [comment]
ok sounds good

**Comment by mcollina** [comment]
Public youtube video: http://youtu.be/qszW6NjzCHA
To join: https://hangouts.google.com/call/ispdwe27u5fgficj6d6mwljqkme

**Comment by mcollina** [comment]
Youtube page: https://www.youtube.com/watch?v=GVcZu6zgyMo
To join: https://hangouts.google.com/call/7d3hacmj2vbvrnncspabfacvzue

**Comment by mcollina** [comment]
Minutes of our meeting:
![streams wg october 2016](https://cloud.githubusercontent.com/assets/52195/19946143/6d351d50-a143-11e6-8274-a1ea9b1120ba.jpeg)

* we slipped some things marked as semver-major in the latest releases, more for safety. Things are currently reviewed before release. However, we might want to look for an automated process in the future.
* we still support old browsers with 1% or less market share, as well as old Node.js versions (down to v0.8). The team goal is to keep supporting those for the time being, and re-evaluate in the next few months.
* reduce the package size: currently this module is downloaded 40 _millions_ time per month, and if we can speed up the downloads by _half a second_, we will still save humanity a huge amount of time.
  * vendor dependencies that we use and maintain #238 (but maybe is better to use `bundleDependencies`, as noted _afterwards_), because we want to keep backward compatibility.
  * remove docs
* @calvinmetcalf will champion `flush()` for `WritableStream`
* @mafintosh will write an EPS on `destroy()`.

## Vendoring readable-stream in core

This was the major topic of the discussion, as we agreed at Interactive EU, we will submit a proposal to have core depend on readable-stream, and not readable-stream pulling from core.

In order to move things forward, I will write an EPS based on the following:

1. we will maintain the build step, as it currently is
2. import the code from nodejs/node into nodejs/readable-stream, and base the build from that
3. vendor readable-stream into core

If things move forward, I would like to present this at the collaborator summit of NINA.

@nodejs/streams, please make edits if things needs changing.
