### ISSUE TITLE
npm package is half doc/stream.md

### ISSUE THREAD

**Issue by yzorg** [nodejs/readable-stream#240]
The readable-stream NPM package, when installed, is 129k.  Half of that size is stream.md, currently 66k.  Why is this (large) doc distributed with the NPM package?  Would you accept a PR to remove it (add doc/ to .npmignore)?

**Comment by DavidTPate** [comment]
@yzorg I would think it is unknowingly included, why not just put in a PR to add it to the `.npmignore`?

**Comment by yzorg** [comment]
I didn't want to assume.  But sure, PR to follow.

**Comment by calvinmetcalf** [comment]
the intent is so that people can see the docs for streams when they install the package

**Comment by calvinmetcalf** [comment]
one thing against including the docs is just that they don't work supper well, some of the links are broken

**Comment by calvinmetcalf** [comment]
fixed in  #242
