### ISSUE TITLE
bundled dependencies

### ISSUE THREAD

**Issue by calvinmetcalf** [nodejs/readable-stream#247]
we bundled our less common dependencies with version 2.2.0, but this immediately causes issues, specifically with yarn (yarnpkg/yarn#1774 and the tl;dr is that the issue was *installing* yarn not using yarn).   The issue seemed to be about upgrading and the dependencies changing place.  So we may need to come up with a different way to bundle them.

**Comment by mcollina** [comment]
IMHO we are in an impossible situation. It shouldn't matter about using bundledDependencies or not.

Anyway, we must bump the major if we want to try again, or have our own version of citgm.

**Comment by calvinmetcalf** [comment]
re citgm it was not fresh installs from what I could tell, just upgrades

**Comment by mcollina** [comment]
Ahum. Looks like it's an npm bug in computing the tree. Sigh. Whenever we bump the major, it will be a nice change to add.
