### ISSUE TITLE
Next WG meeting - January 2017

### ISSUE THREAD

**Issue by mcollina** [nodejs/readable-stream#252]
How about a Streams WG meeting on the week from the 9th to the 12th?

Agenda:

1. #253, usage of `bind()`, and performance across versions of Node and the browser
2. #249, performance degradation using multiple transforms
3. #254, `Symbol.asyncIterator`

Link to join: https://hangouts.google.com/call/2ko57nnswbf6tlmhcksoc5lrz4e
Link to watch: https://www.youtube.com/watch?v=lthLOvt4QV8

**Comment by calvinmetcalf** [comment]
Works for me

**Comment by yoshuawuyts** [comment]
yup, can do

**Comment by benjamingr** [comment]
I'd like to attend and discuss adding support for `Symbol.asyncIterator` as suggested by @mcollina in https://github.com/nodejs/CTC/issues/53. I'll also open a separate issue.

**Comment by mcollina** [comment]
Here is the doodle: http://doodle.com/poll/ws5xvmrps922a46f.

**Comment by mcollina** [comment]
@benjamingr @mafintosh @calvinmetcalf would you mind filling in the doodle? Today is probably out of the equation by now :D.

**Comment by benjamingr** [comment]
It's 4pm, 5pm and 6pm for me - I'm in GMT + 2. I can make 6pm work by leaving work a little early which is fine.,

**Comment by mcollina** [comment]
All times displayed are CET time. Sigh, I set up the doodle wrong.

Here is the correct new doodle: http://doodle.com/poll/wgbmbcwnyiw7g7nz

**Comment by benjamingr** [comment]
Oh, I thought that the doodle automatically aligns to my timezone. I'll update in the new one.

**Comment by mcollina** [comment]
At this point the two most probable dates are:

* Thursday 12th of January at 19:00 CET
* Friday 13th of January at 18:00 CET

Anyone else that want to partecipate please fill in the doodle.
I'm planning to do Thursday 12th of January, 19:00 CET/ 18:00 GMT, if you all agree.

**Comment by calvinmetcalf** [comment]
sounds good

**Comment by lrlna** [comment]
oh hey i am gonna jump in on this one too; thanks for the ping @mcollina

**Comment by mcollina** [comment]
Confirmed for Thursday 12th of January, 19:00 CET/ 18:00 GMT, as stated in the doodle.
I will post a link.

Can we all compose the agenda, we probably have a few things to talk about.

**Comment by calvinmetcalf** [comment]
this the correct time ? https://www.timeanddate.com/worldclock/fixedtime.html?msg=wg+meeting&iso=20170112T19&p1=215&ah=1

**Comment by mcollina** [comment]
@calvinmetcalf yes. Is this still good for you?

**Comment by calvinmetcalf** [comment]
yup just wanted to confirm as time zones are terrible

**Comment by williamkapke** [comment]
Added to the Calendar!
https://calendar.google.com/calendar/embed?src=kap.co_i17i575te0aes6kaanfjr2e4hs%40group.calendar.google.com

**Comment by mcollina** [comment]
@williamkapke should we ping you to add it next time?

**Comment by williamkapke** [comment]
I gave you permission to manage the calendar too- but feel free to ping me.

**Comment by mcollina** [comment]
I've added the links to join or watch at the top.

**Comment by mcollina** [comment]
I would like to talk about my EPS draft in https://gist.github.com/mcollina/ca17ee3de226d8dff6281683ca8c9d24 for the inversion of dependency.

**Comment by yoshuawuyts** [comment]
Something for work came up last minute, gotta cancel. I'll be sure to catch
up with @mafintosh to see what was discussed

**Comment by mcollina** [comment]
Updated link to join https://hangouts.google.com/call/2ko57nnswbf6tlmhcksoc5lrz4e

**Comment by mcollina** [comment]
@lrlna @benjamingr @mafintosh are you folks joining?

**Comment by mafintosh** [comment]
cool meeting! (i joined for the record)

**Comment by benjamingr** [comment]
Sorry I had to miss, personal emergency :(

**Comment by mcollina** [comment]
I'm not really proud of these ones, but here are my notes:

![2017 jan 12 - stream wg 1](https://cloud.githubusercontent.com/assets/52195/21924547/f481e162-d979-11e6-93a2-ca8e333e08f8.jpeg)

![2017 jan 12 - stream wg 2](https://cloud.githubusercontent.com/assets/52195/21924546/f47a5e42-d979-11e6-89b5-d8fd8284d1e8.jpeg)

For a inlined summary:

1. we will be replacing `bind()` for the time being, as it is extremely slow on the old versions of Node. As for the browser, it is less of a problem.

2. @mcollina to investigate if some of the ideas in https://github.com/mcollina/syncthrough can be ported to `Transform`, for the benefits of everyone.

3. as for the inversion of the `readable-state` dependency, some edits where recommended: regarding adding a timeline, and porting the tests so that they can be easily run against the node source, old node builds and the browsers.

4. `Symbol.asyncIterator` can be supported inside streams without internal changes, however merging it inside core depends on what is the adopted change for Promises in core. We are happy to maintain the prototype and expand if needed. We should take care on what is the story for writing to streams, as it should match somehow the story for reading, i.e. we should be able to write with promises as well.

**Comment by lrlna** [comment]
@mcollina dope sketchnotes!! 🖋 📝
