### ISSUE TITLE
add @lrlna to the wg

### ISSUE THREAD

**Issue by lrlna** [nodejs/readable-stream#256]
Hi 👋  -- could I be added to the wg?

**Comment by mafintosh** [comment]
👍

**Comment by mcollina** [comment]
👍

**Comment by yoshuawuyts** [comment]
:+1:

**Comment by Fishrock123** [comment]
cc @nodejs/streams 

@mafintosh and @mcollina you are team maintainers and should be able to do this. I've sent @lrlna an org invitation.

**Comment by lrlna** [comment]
thanks ✨

**Comment by mcollina** [comment]
By our charter, we need a meeting to add new members. We'll do it asap
(let's schedule one for March!)
Il giorno lun 20 feb 2017 alle 17:42 Irina Shestak <notifications@github.com>
ha scritto:

**Comment by lrlna** [comment]
ok, since i am added i'll close this; do you want me to PR the readme @mcollina ?

**Comment by mcollina** [comment]
@lrlna yes!
