### ISSUE TITLE
encoding/setEncoding for objectMode?

### ISSUE THREAD

**Issue by serapath** [nodejs/readable-stream#257]
I'm currently try to learn a bit more about streams.

1. **I read about `setEncoding` and the `encoding` option of readable streams or "readable sides of streams".**
  * When read from read streams, strings are auto-decoded into `strings` with specified encoding.
  * by default this does NOT happen.
  * => Setting the `decodeStrings:false` and making use of `setEncoding` will keep the data in certain pipelines in a certain string encoding and auto-decodes it into that.
2. **I also read about the `decodeStrings` option for writable streams.**
  * So, chunks by default are auto-decoded into `buffers` when written to write streams.
  * by default this DOES happen.
  * => So, streams provide functionality by default to keep data as buffers and turn them back into buffers automatically even if certain streams in the pipeline use strings.

**Is that correct? :-)**

---

**If so - i wonder why there is not similar functionality for `objectMode`.**
*Instead of buffers, chunks are passed around as objects, but in between a different encoding might be necessary (e.g. JSON) or maybe something more optimized to send data to a server or to save it in a database?*
* Is there a way to set something like `decodeObjects:false/true` or `.setEncoding('json')`?
* What are best practices to do those things? (it feels like a solution probably exists already)
* It seems it's not part of core streams contrary to how it is part of core for buffers/strings. Why?

**Comment by calvinmetcalf** [comment]
historically streams were just used for passing around binary data around
(e.g. that's how they are used in node), with object mode arising later,
with tools like JSONStream for converting a binary stream of jsondata into
json objects and back.

**Comment by serapath** [comment]
thx.
I saw JSONStream before. I'm using streams mainly in the browser and i was wondering if there is a build-in mechanism and maybe something smaller.
`JSONStream` has ~250 loc and pulls in `jsonparse` with around ~400 loc and `through` with around ~100 loc ... that feels kind of biggish and it also seems to give more features than i need.

Probably it's all necessary. Until now I was creating transform streams from `require('readable-stream/transform')` and passing functions like:
```js
function data2json (chunk, encoding, next) { // encode
  if (chunk !== null && typeof chunk === 'object') {
    try { chunk = JSON.stringify(chunk) } catch (e) { next(e) }
  }
  next(null, chunk)
}

function json2data (chunk, encoding, next) { // decode
  chunk = chunk.toString()
  if (chunk === 'undefined') chunk = undefined
  try { chunk = JSON.parse(chunk) } catch (e) { chunk = chunk }
  next(null, chunk)
}
```

They seem to do the job, but probably don't work in tons of cases i currently don't think about or haven't encountered yet.

* Do you think transform streams with the above code examples are good enough or is it maybe bad practice for some reasons to do it like that?

* If it is considered to be a good decision to add the encodings features for buffer/strings to streams, is there a chance that the same might happen in the future for objectMode streams? (i feel like i'm writing something like the above code snippets a lot...)

**Comment by calvinmetcalf** [comment]
> Do you think transform streams with the above code examples are good enough or is it maybe bad practice for some reasons to do it like that?

in certain cases that could definitely work, its' not going to work for lazily decodeing the objects of a large array, but if you don't need that it wouldn't be a big deal, the stringify version isn't going to handle comma's but otherwise should be fine

> If it is considered to be a good decision to add the encodings features for buffer/strings to streams, is there a chance that the same might happen in the future for objectMode streams? (i feel like i'm writing something like the above code snippets a lot...)

probably not, your basically asking for json stream to be part of core, after previously suggesting that it was too big for what you wanted, adding it in would mean that everyone would get it even if they didn't need it, my suggestion is to just use jsonstream as it's not very large compared to the rest of streams.

**Comment by serapath** [comment]
cool. i'll do that then. thx :-)

**Comment by serapath** [comment]
oh, one more thing.

I tried to find all "encodings" supported by node streams, but couldnt find it here:
https://nodejs.org/api/stream.html

On stackoverflow i found the list of: `ascii, base64, binary, hex, ucs2/ucs-2/utf16le/utf-16le`
I tried with `.setEncoding(...)`, but it throws if it's an unknown encoding.

* **Is it possible to set custom encodings?**

When i send data from a buffer/string stream to an objectMode stream, i sometimes might receive `"1"` which is meant to represent the string `"1"` and sometimes the number `1`, so I imagine i would like to set some kind of "encoding" to tell whether it's a string/boolean/object/undefined/number/...

* **Is there something like that?**
* **Or what is the reasoning why something like that does not exist?**

-----

To maybe put it different. The most common case i run into all the time is, that in the browser i use objectMode streams all the time, but when i send it to a backend or retrieve it from a backend via streams, i need to translate it to buffer/strings. ... and it always causes problems to, for example, get back a `"1"` or a `1`, when it was once stored in the backend and then received back from it in a future session.

* **How can i make that use case really simple?**
* **How do people deal with it? Do they invent their custom solutions and wrap data into JSON and maybe invent a "type" property to specify if it's a "string" or a "number"?**

**Comment by calvinmetcalf** [comment]
encoding are the same ones as buffer, so full list here
https://nodejs.org/api/buffer.html#buffer_buffers_and_character_encodings

yes if you need to handle typed data you should use a typed transport
mechanism like json or protobuffs, objectMode streams tread the data as
opaque objects

**Comment by derhuerst** [comment]
> encoding are the same ones as buffer

Would be useful to have this information more explicitly in the docs.

> How do people deal with it? Do they invent their custom solutions and wrap data into JSON and maybe invent a "type" property to specify if it's a "string" or a "number"?

I often see this:

```js
# client/browser
myCustomData
.pipe(ndjson.stringify())
.pipe(someStreamingTransport)

# server/node
const myCustomData = someStreamingTransport
.pipe(ndjson.parse())
```

**Comment by serapath** [comment]
cool thx :-)
