### ISSUE TITLE
Limit concurrent build in travis

### ISSUE THREAD

**Issue by mcollina** [nodejs/readable-stream#265]
I think this repository would benefit a limit to the concurrent builds in Travis to 1. This might help reducing the localtunnel failures:

https://docs.travis-ci.com/user/customizing-the-build#Limiting-Concurrent-Builds

cc @calvinmetcalf @addaleax @williamkapke

**Comment by calvinmetcalf** [comment]
ok that sounds sensible

**Comment by calvinmetcalf** [comment]
@Fishrock123 you've done this for us in the past

**Comment by Fishrock123** [comment]
I can do it but I will probably get quite a bit of heat for doing so again if it still requests private access. I have reached out to travis to confirm whether their split perms now properly apply for organizations or not.

**Comment by mcollina** [comment]
@Fishrock123 what will be the best approach if not? We move `readable-stream` to core CI infrastructure?

**Comment by Fishrock123** [comment]
Probably move either the private stuff or this stuff to a new org as has been discussed before. What a mess.

**Comment by Fishrock123** [comment]
Unless you really want to build for and consume core ci resources...

**Comment by mcollina** [comment]
I'm 👍  in moving to our own org, if it's not a problem for the rest of the collaborators. It might make GitHub teams more fuzzy though.

**Comment by addaleax** [comment]
Are we talking about moving `readable-stream` out of the `nodejs` github org? I am *not* sure I feel very positive about that. It should definitely be visible that the work here ultimately happens under the Foundation/TSC…

Other projects like node-inspect or citgm (as a project on its own) also use the Core CI infra, so there’s certainly precedent for that.

**Comment by calvinmetcalf** [comment]
yeah I'm with @addaleax I'd prefer to only do that as a last resort

**Comment by Fishrock123** [comment]
Going to email travis support. Hopefully we'll hear back.

**Comment by mcollina** [comment]
@Fishrock123 did you hear anything back? I think we might just have to move to the foundation CI system.

**Comment by mcollina** [comment]
This is not possible, we are moving to the Foundation CI.
