### ISSUE TITLE
Bring string_decoder into the foundation

### ISSUE THREAD

**Issue by mcollina** [nodejs/readable-stream#272]
Very recently a bug was reported to [string_decoder](https://github.com/rvagg/string_decoder), and @rvagg forwarded it to me.  (a test is failing in node 4+).

That module uses a very similar machinery to readable-stream to keep it in sync with latest Node.js. I'm in the process of updating that as well to the latest node.js.

Speaking with @rvagg, I think it might be a good idea to move it under the nodejs github organization, and we keep that in sync together with `readable-stream`. 

Do you all agree it's a good idea?

**Comment by calvinmetcalf** [comment]
is this the one browserify uses ?

**Comment by mcollina** [comment]
yes.

**Comment by mcollina** [comment]
We also depend on that: https://github.com/nodejs/readable-stream/blob/master/package.json#L12

**Comment by calvinmetcalf** [comment]
we also rely on [process](https://github.com/defunctzombie/node-process), that might be a good one to move over to the node umbrella too, that being said it's very different from string_decoder or this as it's a shim that attempts to simulate node behavior

**Comment by mcollina** [comment]
@calvinmetcalf I think string_decoder is lifted from core, and as such I think it should be under the foundation.

**Comment by mcollina** [comment]
I've tagged this @nodejs/ctc, as I think it's the best course of action.

**Comment by joshgav** [comment]
This should be reviewed by the TSC too, added label.

**Comment by mcollina** [comment]
@nodejs/ctc has no problem in this if @nodejs/tsc is ok with it.

**Comment by mhdawson** [comment]
This looks familiar was there another issue where people were asked to weigh in  or was that a different package ?

**Comment by joshgav** [comment]
@mhdawson 

ref: https://github.com/nodejs/TSC/issues/260

**Comment by mhdawson** [comment]
@joshgav thanks, wanted to make sure I had chimed into the conversation.

**Comment by mcollina** [comment]
This has been done, and we can close this.
