### ISSUE TITLE
Exclude `buffer-shims` from browser build

### ISSUE THREAD

**Issue by feross** [nodejs/readable-stream#281]
The browser implementation of [`buffer`](https://github.com/feross/buffer) (used by `browserify` and `webpack`) supports the new buffer methods (`Buffer.from`, etc.) so there is no need to use `buffer-shims` in the browser.

Let's exclude `buffer-shims` and just use `Buffer.from`, etc. directly in the browser to save sending 7.44 kB of extra code that is never used.

**Comment by calvinmetcalf** [comment]
I was actually thinking of switching to safe buffer

**Comment by mcollina** [comment]
@feross we need `buffer-shims` (or `safe-buffer`) because we must support old Node.js version, not just the browser. How should we do that in browserify?

**Comment by RangerMauve** [comment]
Maybe you could have a file called `buffer-impl.js` which in the browser would return `global.Buffer` and in Node return `safe-buffer`? Or better yet, have a browser alias for `safe-buffer` which points to a file which exports `global.Buffer`

**Comment by calvinmetcalf** [comment]
I think [safe-buffer](https://github.com/feross/safe-buffer) does everything we need, I probably wouldn't have written buffer-shim if I know about it

**Comment by feross** [comment]
> @mcollina we need buffer-shims (or safe-buffer) because we must support old Node.js version, not just the browser. How should we do that in browserify?

I think you probably already figured it out, but just documenting for others. In the browser `require('safe-buffer')` is just an alias for `require('buffer')` which already has all the needed methods. See [`browser.js`](https://github.com/feross/safe-buffer/blob/6ed80179e4847e49781de0587eedae5d7d658949/browser.js).
