### ISSUE TITLE
Next WG meeting - June 2017

### ISSUE THREAD

**Issue by mcollina** [nodejs/readable-stream#285]
Hi Folks

Given our bimonthly meetings, it's time we start planning when we want to run the next streams-wg meeting :).

Agenda: 

* <strike>Status of `destroy()`: https://github.com/nodejs/node/pull/12925</strike>
* <strike>Status of  `_final()`: https://github.com/nodejs/node/pull/12828</strike>
* Status of on the use of `_readableState` and `_writableState` in core https://github.com/nodejs/node/issues/7629.
* Schedule for bumping the major https://github.com/nodejs/readable-stream/issues/284
* Automatic string decoding for writable streams https://github.com/nodejs/node/issues/7315
* `stream.end(chunk, enc, cb)` should always call the callback https://github.com/nodejs/node/issues/5540

I'll set up a doodle for the date

Invited @jessicaquynh - she wrote https://github.com/nodejs/nodejs.org/blob/f6bfed8438d8a88eb52ee0a623b56152cf8f95ae/locale/en/docs/guides/backpressuring-in-streams.md

**Comment by mcollina** [comment]
Here is the doodle: http://doodle.com/poll/g634n3b4vxpgitbmd8it3hv7 cc @nodejs/streams

**Comment by calvinmetcalf** [comment]
doodle doesn't work

**Comment by calvinmetcalf** [comment]
didn't mean to close

**Comment by mcollina** [comment]
new link, hope this works: https://doodle.com/poll/g634n3b4vxpgitbm

**Comment by mcollina** [comment]
I'm picking Wednesday 21st, June, at 17:00 CEST, 8:00 PDT.

**Comment by mcollina** [comment]
Ping! Hey folks, quiet remember of today's meeting!

**Comment by mcollina** [comment]
Both @lrlna and @yoshuawuyts cannot join the meeting. Will there be someone else?

To watch: https://www.youtube.com/watch?v=903Gj69LOYU
To join: https://hangouts.google.com/hangouts/_/bugq55awmndi5eqjnnhslqzviue

**Comment by jessicaquynh** [comment]
@mcollina I can join but mostly to watch!

**Comment by mcollina** [comment]
We are rescheduling because there not enough members.

@lrlna @yoshuawuyts @mafintosh what days would you prefer?

**Comment by yoshuawuyts** [comment]
I can do tomorrow before 5pm CET and after 6pm CET, free the rest of the
week (:

**Comment by lrlna** [comment]
sorry about today! I can do tomorrow before 7 CET and anytime for the rest
of the week.
