### ISSUE TITLE
Not Support Node V8.0

### ISSUE THREAD

**Issue by openroc** [nodejs/readable-stream#289]

**Comment by mcollina** [comment]
why? what's the error?

**Comment by openroc** [comment]
sorry for missing the details. when I built ionic under node v8, and found this error,

_stream_readable.js:545
  switch (state.pipesCount) {
               ^

TypeError: Cannot read property 'pipesCount' of undefined
    at module.exports.Readable.pipe (_stream_readable.js:545:16)


and I found these topics, https://github.com/ionic-team/ionic/issues/11872,  https://github.com/ionic-team/ionic-cli/issues/2375,

someone saied that Node 7.10 works fine for me, but I get this error with Node 8.

**Comment by mcollina** [comment]
There is a bug in Node 8.0.0, Node 8.1 will address this regression: https://github.com/archiverjs/node-archiver/issues/236#issuecomment-306480008.

**Comment by openroc** [comment]
thanks a lot
