### ISSUE TITLE
isarray module is deprecated

### ISSUE THREAD

**Issue by MikailBag** [nodejs/readable-stream#300]

**Comment by calvinmetcalf** [comment]
true though

- the version we use doesn't display a depreciation notice
- it's on our list of things to deal with at some point but it would require a major version bump which we don't want to do anytime soon

**Comment by GiedriusGrabauskas** [comment]
You can find deprecation notice in [README file](https://github.com/juliangruber/isarray/blob/master/README.md#isarray).

**Comment by mcollina** [comment]
The module has been undeprecated, and I just fired https://github.com/juliangruber/isarray/pull/18 to remove the notice in the README.

Closing this issue.
