### ISSUE TITLE
Stream WG meeting - September 2017

### ISSUE THREAD

**Issue by mcollina** [nodejs/readable-stream#309]
Hi Folks

Given our <strike>bimonthly</strike> meetings, it's time we start planning when we want to run the next streams-wg meeting :).

Agenda: 

* Status of on the use of `_readableState` and `_writableState` in core https://github.com/nodejs/node/issues/7629.
* Schedule for bumping the major https://github.com/nodejs/readable-stream/issues/284
* Automatic string decoding for writable streams https://github.com/nodejs/node/issues/7315
* `stream.end(chunk, enc, cb)` should always call the callback https://github.com/nodejs/node/issues/5540
* Support the new error system from core #297 

<strike>Here is a doodle: https://doodle.com/poll/ydqhpfc3tksiqr4t</strike>

The meeting will take place over hangouts (links to follow) on Tuesday 12th of September at 16:00 GMT.

London time: 17:00
Paris time: 18:00
Portland time: 9:00

-- I hope the times are right. Please check.

Watch at: http://youtu.be/pzHK1iJVGic

cc @jessicaquynh @jasnell.

**Comment by yoshuawuyts** [comment]
@mcollina replied! - could you ping people once a date has been decided? Thanks!

Also cc/ @nodejs/streams

**Comment by lrlna** [comment]
@mcollina, filled out!

**Comment by mcollina** [comment]
Based on the doodle responses, the meeting will take place Tuesday 12th of September at 16:00 GMT.

I can send a calendar invite, and will ping again one or two days prior to the meeting!

**Comment by lrlna** [comment]
cool, thanks Matteo!

**Comment by mcollina** [comment]
cc @jessicaquynh?

**Comment by sonewman** [comment]
can i join?

**Comment by mcollina** [comment]
@sonewman yes!!!! Come in!

**Comment by mcollina** [comment]
PR to add the Error: https://github.com/nodejs/node/pull/15042

**Comment by sonewman** [comment]
@mcollina sorry I didn't have so much to contribute, I will have to spend sometime familiarising myself with the code again before the next meeting!

**Comment by mcollina** [comment]
### Status of on the use of _readableState and _writableState in core

Hoping for a vote in the next TSC. For us it does not matter, it was requested by core.

### Bumping the major

- we need to handle the new Error codes as semver-major?
- we will take our time if needed

### Errors - https://github.com/nodejs/readable-stream/issues/297

- custom error types are very hard to do in browsers, we cannot do them (Calvin, Yosh, Irina)
- codes we can do
- We can replace `new error.Error(code)` with `buildError(code)` and we would need to ship our messages bundled.
- We can then decide if it's semver-major or not (depends if we change the error messages).

### Automatic string decoding for writable streams nodejs/node#7315

See our response in: https://github.com/nodejs/node/issues/7315#issuecomment-328918557

### stream.end(chunk, enc, cb) should always call the callback nodejs/node#5540

See our response in: https://github.com/nodejs/node/issues/5540#issuecomment-328915928

**Comment by mcollina** [comment]
@sonewman no worries! Thanks for joining!

**Comment by jessicaquynh** [comment]
@mcollina Sorry I missed this! I got the date wrong, is there a recording I can listen to?

**Comment by mcollina** [comment]
The youtube link above should work:  http://youtu.be/pzHK1iJVGic
