### ISSUE TITLE
Constructor chain fails (somehow) when cache is modified after readable-stream loading

### ISSUE THREAD

**Issue by iarna** [nodejs/readable-stream#312]
@mcollina 

As seen on Twitter, there's an unfortunate interaction between `require-inject`, which requires the `require.cache` after each use and `readable-stream`.  A repro for this can be found here:

https://gist.github.com/iarna/846412c9e41064a0e472b7d7e40d51a4

I'm honestly baffled as to _why_ the readable-stream instanceof checks are failing. Once I have a copy of the class I'd expect the constructors to work regardless of the state of the `require.cache`.

**Comment by mcollina** [comment]
I think it might be due to https://github.com/nodejs/readable-stream/blob/master/lib/internal/streams/stream.js. For historical reason, we are inheriting from a core module, and maybe some "old" references to that keep lingering around.
