### ISSUE TITLE
process.version.slice - undefined is not an object

### ISSUE THREAD

**Issue by gwmccull** [nodejs/readable-stream#313]
It appears that not all environments that are using this library pass a `process.version`.

Some of the libraries that I use in React Native are using this library at run-time and are not passing a version.  Since version is undefined, the slice method fails.

**Comment by calvinmetcalf** [comment]
is process.verison missing or process itself ?

**Comment by gwmccull** [comment]
process and process.ENV are defined but not process.version

**Comment by gwmccull** [comment]
I found out that you can polyfill `process.version` by creating a globals file and specifying the missing `process` properties there.  That's probably the best way to go rather than try to "fix" all of the Node libraries

**Comment by Kishanjvaghela** [comment]
@gwmccull How to create global file?

**Comment by gwmccull** [comment]
@kishanjvaghela I think I did something like this:
https://stackoverflow.com/a/42149659

1. Create global.J's
2. Add global.process.version to it as a JS variable
3. Make sure global.J's is imported as one of the first files in my project

I'm no longer on that project but those steps should get you close

**Comment by Kishanjvaghela** [comment]
Thanks a lot
