### ISSUE TITLE
TypeError: this.once is not a function

### ISSUE THREAD

**Issue by FreedCapybara** [nodejs/readable-stream#315]
Hello,

I have a project that uses Webpack and I'm getting the error `TypeError: this.once is not a function` inside of `_stream_duplex.js`:
```js
function Duplex(options) {
  if (!(this instanceof Duplex))
    return new Duplex(options);

  Readable.call(this, options);
  Writable.call(this, options);

  if (options && options.readable === false)
    this.readable = false;

  if (options && options.writable === false)
    this.writable = false;

  this.allowHalfOpen = true;
  if (options && options.allowHalfOpen === false)
    this.allowHalfOpen = false;

  this.once('end', onend); // <--- this guy
}
```
Please see this issue for more details https://github.com/mqttjs/MQTT.js/issues/696

Thank you!

**Comment by mcollina** [comment]
Can you please prove a way to reproduce it?

**Comment by FreedCapybara** [comment]
You'll have to forgive me because my steps to reproduce come from projects that use readable-stream as a dependency (mqtt stuff), but here you go:
1. Set up [Angular Starter](https://github.com/AngularClass/angular-starter) (I just downloaded the zip instead of cloning)
2. `npm install --save ngx-mqtt`
3. Set up ngx-mqtt in `src/app/app.module.ts`:
```js
// ...
import {
  MqttModule
  MqttMessage
  MqttService
} from 'ngx-mqtt';

export const MQTT_SERVICE_OPTIONS = {
  hostname: 'iot.eclipse.org',
  port: 80,
  path: '/ws'
}

export function mqttServiceFactory() {
  return new MqttService(MQTT_SERVICE_OPTIONS);
}

// ...
@NgModule({
  // ...
  imports: [
    // ...
    MqttModule.forRoot({
      provide: MqttService,
      useFactory: mqttServiceFactory
    })
  ]
})
```
4. Inject MqttService in `src/app/home/home.component.ts`:
```js
// ...
import { MqttService } from 'ngx-mqtt';

export class HomeComponent implements OnInit {

  constructor(
    // ...
    private ngxMqttService: MqttService
  ) {}
}
```
5. `npm start` and navigate to localhost:5000
6. Check your browser console (I used Chrome)

**Comment by FreedCapybara** [comment]
It looks like something in the Angular Starter configuration causes problems with the prototype assignment (see this issue)[https://github.com/isaacs/once/issues/1] and [the once.js source](https://github.com/isaacs/once/blob/master/once.js).

Perhaps the file could be adjusted to avoid relying on the prototype assignment?

**Comment by FreedCapybara** [comment]
Just from messing with the files in my node_modules, it seems like changing _stream_duplex.js as follows solves this issue (but causes different errors with this project setup):
```js
var once = require('once');

function Duplex(options) {
  // ...
  once('end', onend);
}
```
After making this adjustment I get `TypeError: Cannot set property 'needReadable' of undefined` inside of _stream_transform.js.

**Comment by mcollina** [comment]
@FreedCapybara can you upload all the steps in https://github.com/nodejs/readable-stream/issues/315#issuecomment-336526623 in a github repo so that we can speed up the process? Thanks.

**Comment by FreedCapybara** [comment]
Thanks @mcollina, here you go: https://github.com/FreedCapybara/reproduce-mqtt-issue

**Comment by FreedCapybara** [comment]
It seems like it's just little things, where ensuring that everything is defined would fix issues with TypeScript/Webpack-like environments 👍

**Comment by mcollina** [comment]
What's should I do to reproduce the issue on that repo?

**Comment by FreedCapybara** [comment]
Just run the app with `npm start`. You should see the error in your console.

**Comment by mcollina** [comment]
I've just run it, and it works smoothly here. There is no error in the console.

**Comment by FreedCapybara** [comment]
Alright, well, up to you if you want to do anything about it, then ¯\_(ツ)_/¯

Ensuring everything is defined would be a good thing to do to make the code more robust, but I guess it's not a big deal if I'm the only person running into this.

I ended up using a different mqtt library, so I'm not really blocked by this issue anymore. Closing.

**Comment by stewhi** [comment]
Ran into the exact same thing, would highly recommend taking FreedCapybara's fix, it worked like a charm.

**Comment by mcollina** [comment]
As I said, can somebody shows me instructions to reproduce?
When I run the example above, I got no error and it seemed a cache/bug in the transpiler or bundler or package manager as starting fresh did not cause any problems here.
We cannot fix something that we cannot reproduce.

**Comment by stewhi** [comment]
Mine was 
```
import * as jwt from "jsonwebtoken";
const token = jwt.sign(
            {    
                documentId,
                permission: "read:write",   
                tenantId,    
                user: {    
                    id: userId,    
                },    
            },    
            secret);
```
On hitting this, it eventually ended up in stream, where it would throw the error `this.once` is not a function.

**Comment by chromakode** [comment]
Apologies for bumping a dead thread. I've just run into this and want to add some additional context to the top google result. 

I'm running a pika build of readable-stream here: https://cdn.pika.dev/-/readable-stream@v3.6.0-OKumKRBjsyH8yLExcy0D/dist=es2019/readable-stream.js

The bundle contains the following lines (in this order):

```
inherits(Duplex$1, _stream_readable);
...
var _stream_readable = Readable;
...
function Readable(options) {
```

At the time `inherits(Duplex$1, _stream_readable)` runs, `_stream_readable` is hoisted but not yet defined, which is why `Duplex.once` ends up not defined.

This appears to be an issue with the source transforms of some bundlers, not caused by `readable-stream` itself.
