### ISSUE TITLE
sinon/lolex fake timers broken when used with this

### ISSUE THREAD

**Issue by kolodny** [nodejs/readable-stream#316]
Consider the following mocha test file

```js
var lolex = require('lolex');
var through = require('through2');

describe('a bug', function() {
  var clock;
  before(function() {
    clock = lolex.install({toFake: [ 'setImmediate', 'nextTick' ]});
  });
  after(function() {
    clock.uninstall();
  });

  it('does not work well with lolex', function(done) {
    var stream = through.obj();
    stream.on('data', function() {
      stream.on('end', function() {

        console.log('creating stream2')
        var stream2 = through.obj();
        stream2.on('data', function() {
          stream2.on('end', function() {
            console.log('OK')
            done();            
          });
          setImmediate(function() {
            stream2.end()
          });
        });
        stream2.emit('data')

      });
      stream.end();
    });
    stream.emit('data');

    clock.runAll()
  });

});

```

When the `clock` calls are removed and this runs using regular time this runs and finishes as expected and without errors. However when running with lolex `install`ed it just hangs after logging `creating stream2`. This is due to https://github.com/nodejs/readable-stream/blob/d6c391d7101946c8b8b97914fc46fd3322c450d1/lib/_stream_readable.js#L983 which retains a reference to the non swapped out version of `process.nextTick` due to use of `process-nextick-args` https://github.com/nodejs/readable-stream/blob/d6c391d7101946c8b8b97914fc46fd3322c450d1/lib/_stream_readable.js#L26

A simple solution can be swapping `require('process-nextick-args')` with `require('./process-nextick-args')` which can look something like this:

```js
//  ./process-nextick-args
var nextTickNeedsPatching = (
  !process.version ||
  process.version.indexOf('v0.') === 0 ||
  process.version.indexOf('v1.') === 0 && process.version.indexOf('v1.8.') !== 0
);

var processNextTick = function(fn, a, b, c) {
  return !nextTickNeedsPatching ? process.nextTick(fn, a, b, c) :
  process.nextTick(function() {
    fn(a, b, c);
  });
  
}
```

Does that sound like a reasonable solution?

**Comment by kolodny** [comment]
`lolex` is the module powering `sinon` fake timers so this issue affects anyone using `sinon` fake timers too.

**Comment by calvinmetcalf** [comment]
you probably want to open something on process-nextick-args

**Comment by kolodny** [comment]
Good call. https://github.com/calvinmetcalf/process-nextick-args/pull/10

**Comment by calvinmetcalf** [comment]
reopening as we now need to update process.nextick-args

**Comment by benjamingr** [comment]
Hey, I can fix this from the lolex side (I wrote the nextTick part there) - is this still an issue?

**Comment by benjamingr** [comment]
Note lolex doesn't override microtask stuff by default.

**Comment by kolodny** [comment]
Yeah, this is still an issue. I resorted to [patching the relevant files](https://github.com/googleapis/nodejs-bigtable/tree/master/patches) until the nextTick fixes makes it's way to node, but fixing it in lolex would be better. I didn't realize that was an option

**Comment by benjamingr** [comment]
I'm not sure I understand the issue completely - but I'm willing to patch it on either side (lolex or Node.js). How would a fix from the lolex side look like?

**Comment by kolodny** [comment]
I'm not sure how to go about a fix from the `lolex` side, I think that `readable-stream` needs to update the dependency of `process-nextick-args`
