### ISSUE TITLE
Update isArray please to 2.x

### ISSUE THREAD

**Issue by Croydon** [nodejs/readable-stream#318]
Please update isArray to 2.x

Dependencies checks are kinda annoying us with deprecated warnings right now 🙈

**Comment by mcollina** [comment]
I would reccomend to fine-tune your checks, there is very little need to check this module.

I would see if we can update this dependency, but all the code that is there is fine.

**Comment by Croydon** [comment]
I just noticed this: https://github.com/nodejs/readable-stream/commit/66aa1ca5b635305cfc6fc518149be8034a78fe9c

Depending on which Node.js versions you want to support the dependecy might not be required anymore.

**Comment by mcollina** [comment]
version 2 is deprecated. The actual path is removing the dependency, and we will do this in the next major because v2 still support old versions of Node and Browsers that do not have `Array.isArray()`.
