### ISSUE TITLE
React Native support?

### ISSUE THREAD

**Issue by mjmasn** [nodejs/readable-stream#319]
I'm using this package in place of `stream` via a module-resolver alias in my `.babelrc` for React Native. Unfortunately it throws an error because process is undefined until the entry point (index.js) of the app, at which point this module has already been imported.

Would you be interested in a PR to support this use case? The relevant change is fairly simple: https://github.com/mjmasn/readable-stream/commit/12d241556561cccd6258a783e2e68cf2bee5fb2b

I published a scoped package with the fix but ideally would be able to use the official package. Any thoughts?

**Comment by calvinmetcalf** [comment]
shouldn't babel be able to import process before this?

**Comment by mjmasn** [comment]
@calvinmetcalf I couldn't find a 'babel config' way, but on second thoughts, the solution is just move the `global.X =  Y` declarations into a separate shim file, then import that file rather than declaring the globals directly in index.js.
