### ISSUE TITLE
processNextTick is not a function

### ISSUE THREAD

**Issue by coljung** [nodejs/readable-stream#321]
Hi there,

I have a local project and something somewhere is running _stream_readable.

I'm getting this error since yesterday:

```
/code/node_modules/readdirp/node_modules/readable-stream/lib/_stream_readable.js:783
    processNextTick(resume_, stream, state);
    ^

TypeError: processNextTick is not a function
    at resume (/code/node_modules/readdirp/node_modules/readable-stream/lib/_stream_readable.js:783:5)
    at ReaddirpReadable.Readable.resume (/code/node_modules/readdirp/node_modules/readable-stream/lib/_stream_readable.js:775:5)
    at ReaddirpReadable.Readable.on (/code/node_modules/readdirp/node_modules/readable-stream/lib/_stream_readable.js:745:53)
    at FSWatcher.<anonymous> (/code/node_modules/chokidar/lib/nodefs-handler.js:362:8)
    at FSWatcher.NodeFsHandler._handleDir (/code/node_modules/chokidar/lib/nodefs-handler.js:406:18)
    at FSWatcher.<anonymous> (/code/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/code/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:153:5)
```

Also, im unsure as to what plugin is causing this issue.

Thanks in advance and i hope this is the right place to ask this question.

**Comment by jasnell** [comment]
Posting an issue in https://github.com/nodejs/readable-stream would be the right place to start. If it turns out to be an issue with core itself, come back here :-) ... when you open the issue over in the readable-stream repo, ping @mcollina to take a look :-)

**Comment by mcollina** [comment]
This is readable-stream @jasnell .

**Comment by jasnell** [comment]
HA!!! Oh my, I need more coffee!

**Comment by mcollina** [comment]
Can you send an example to reproduce your issue? It seems you might have an issue with your dependencies. You should probably reinstall whatever you are using.

**Comment by Lars-Kristian** [comment]
@mcollina We have the same issue. I believe it comes from mgtt.js but I am not sure. I have to do some more testing.

`processNextTick` seems to be `undefined` in this code block.

```function resume(stream, state) {
  if (!state.resumeScheduled) {
    state.resumeScheduled = true;
    processNextTick(resume_, stream, state);
  }
}```

**Comment by Lars-Kristian** [comment]
The issue occurs only on minified code, and this is the callstack.
```connect in mqtt.js creates MqttClient(wrapper, opts)
MqttClient calls this._setupStream()
MqttClient.prototype._setupStream calls this.stream.pipe(writable)
src.on('data', ondata)
Readable.prototype.on calls this.resume()
Readable.prototype.resume calls resume(this, state)
inside resume processNextTick is undefined.

**Comment by mcollina** [comment]
How are you bundling? Which tool are you using? Can you spin up a simple repository to reproduce the bug?

**Comment by andrewjjohnson** [comment]
I had the same error, TypeError: processNextTick is not a function. In my case I was unknowingly using an older version of readable-stream.

The module process-nextick-args is returning an object with the 'nextTick' property containing the function you need. In the updated version of readable-stream, it correctly imports it as:
'var processNextTick = ("process-nextick-args").nextTick'
 vs the old way, which you are probably using, 
'var processNextTick = ("process-nextick-args")'

When I looked at the stack trace to see what module started it all, I noticed that the module correctly had the most updated readable-stream in it's node modules, but I also had an outdated version of readable-stream in the top layer of my node modules folder, so everything was using that one. Once I updated that in my node modules to 3.3.4, everything worked fine.

I hope that helps,
Thank you

**Comment by ajbeach2** [comment]
I am also having an issue with this. It is a dependency of webpack dev server. 

```
turner_launchpad_app_1  | /usr/src/app/node_modules/readdirp/node_modules/readable-stream/lib/_stream_readable.js:783
turner_launchpad_app_1  |     processNextTick(resume_, stream, state);
turner_launchpad_app_1  |     ^
turner_launchpad_app_1  | 
turner_launchpad_app_1  | TypeError: processNextTick is not a function
turner_launchpad_app_1  |     at resume (/usr/src/app/node_modules/readdirp/node_modules/readable-stream/lib/_stream_readable.js:783:5)
turner_launchpad_app_1  |     at ReaddirpReadable.Readable.resume (/usr/src/app/node_modules/readdirp/node_modules/readable-stream/lib/_stream_readable.js:775:5)
turner_launchpad_app_1  |     at ReaddirpReadable.Readable.on (/usr/src/app/node_modules/readdirp/node_modules/readable-stream/lib/_stream_readable.js:745:53)
turner_launchpad_app_1  |     at FSWatcher.<anonymous> (/usr/src/app/node_modules/watchpack/node_modules/chokidar/lib/nodefs-handler.js:362:8)
turner_launchpad_app_1  |     at FSWatcher.NodeFsHandler._handleDir (/usr/src/app/node_modules/watchpack/node_modules/chokidar/lib/nodefs-handler.js:406:18)
turner_launchpad_app_1  |     at FSWatcher.<anonymous> (/usr/src/app/node_modules/watchpack/node_modules/chokidar/lib/nodefs-handler.js:455:19)
turner_launchpad_app_1  |     at FSWatcher.<anonymous> (/usr/src/app/node_modules/watchpack/node_modules/chokidar/lib/nodefs-handler.js:460:16)
turner_launchpad_app_1  |     at FSReqWrap.oncomplete (fs.js:171:5)
```

**Comment by ajbeach2** [comment]
Updating webpack seems to have fixed my issues 
```
-    "webpack-dev-server": "^2.9.4",
-    "webpack-merge": "^4.1.1"
+    "webpack-dev-server": "^2.11.0",
+    "webpack-merge": "4.1.1"
```

**Comment by yangzj1992** [comment]
also have same issue 

> TypeError: processNextTick is not a function
 (err):     at emitReadable (/node_modules/bl/node_modules/readable-stream/lib/_stream_readable.js:419:21)
 (err):     at onEofChunk (/node_modules/bl/node_modules/readable-stream/lib/_stream_readable.js:407:3)
 (err):     at readableAddChunk (/node_modules/bl/node_modules/readable-stream/lib/_stream_readable.js:176:5)
 (err):     at BufferList.Readable.push (/node_modules/bl/node_modules/readable-stream/lib/_stream_readable.js:157:10)
 (err):     at BufferList.destroy (/node_modules/bl/bl.js:211:8)
 (err):     at Request.<anonymous> (/node_modules/request/request.js:1023:14)
 (err):     at emitOne (events.js:77:13)
 (err):     at Request.emit (events.js:169:7)
 (err):     at IncomingMessage.<anonymous> (/node_modules/request/request.js:965:12)
 (err):     at emitNone (events.js:72:20)
 (err):     at IncomingMessage.emit (events.js:166:7)
 (err):     at endReadableNT (_stream_readable.js:921:12)
 (err):     at nextTickCallbackWith2Args (node.js:442:9)
 (err):     at process._tickDomainCallback (node.js:397:17)

**Comment by mcollina** [comment]
@yangzj1992 can you post an example to reproduce?

**Comment by coljung** [comment]
My error was fixed when i updated my package.json actually. I guess a package dependency was broken with an update somewhere along the line, and that was fixed.

I think ( not sure ), the culprit on my side might have been webpack-dev-server.

In any case, try to run npm outdated / npm update and see if the updates fix the issue.

**Comment by rbecheras** [comment]
I recently got the same issue but only with node v6 (boron) & v7.

It don't have the issue with v8 (carbon) & v9.

See this travis  build jobs list: https://travis-ci.org/sirap-group/generate-swap-project/builds/370127767?utm_source=github_status&utm_medium=notification

![capture d ecran de 2018-04-23 16-52-41](https://user-images.githubusercontent.com/6469390/39134396-d0b50e10-4716-11e8-9c33-73928950513b.png)

See also the two failing job logs:

* The job with v6: https://travis-ci.org/sirap-group/generate-swap-project/jobs/370127772
* the job with v7: https://travis-ci.org/sirap-group/generate-swap-project/jobs/370127771

The source repository: https://github.com/sirap-group/generate-swap-project

**Comment by mcollina** [comment]
Sadly, this is not a bug on our side. Somewhere in your toolchain this module is wrongly resolved. My best bet is yarn as we had a lot of problems with it in the past.
Update your dependencies/lock files and it should be good.
