### ISSUE TITLE
Wrong listener removed?

### ISSUE THREAD

**Issue by arj03** [nodejs/readable-stream#322]
Grepping through code to find memory leaks this line looks suspicious:

https://github.com/nodejs/readable-stream/blob/master/lib/_stream_readable.js#L597

Should that be 'unpipe'?

**Comment by mcollina** [comment]
No, https://github.com/nodejs/readable-stream/blob/master/lib/_stream_readable.js#L561-L562. It is added to the `'end'` listener, not `'unpipe'`.
