### ISSUE TITLE
process-nextick-args used incorrectly

### ISSUE THREAD

**Issue by kolodny** [nodejs/readable-stream#323]
[The whole point of the change in `process-nextick-args` was to enable fake timers to work with this module. The way this was supposed to be accomplished was by making the nextTick property a "live" binding.](https://github.com/calvinmetcalf/process-nextick-args/pull/10) In https://github.com/nodejs/readable-stream/commit/41a330137ce9cda5a95ef23d5454c70acb9c962a#diff-279988bef5e6fbf7ed82cae28ecc2d59L128 this was changed to keep a reference to a potentially stale function. I'm not sure how to go about changing the generated code to make this change, else I would just make a PR.

**Comment by mcollina** [comment]
You need to fix it in this block: https://github.com/nodejs/readable-stream/blob/master/build/files.js#L127-L136.
Then `cd build; npm i; node build.js 8.9.4`. Should do the trick.

If you could also add a test, it would be awesome. Place it under https://github.com/nodejs/readable-stream/tree/master/test/ours.

**Comment by mcollina** [comment]
Fixed in 2.3.5
