### ISSUE TITLE
Events module not in package.json

### ISSUE THREAD

**Issue by mahatosourav91** [nodejs/readable-stream#327]
Hi, I am getting the following error,
error: bundling failed: Error: Unable to resolve module `events` from ``/Users/node_modules/redux-persist-transform-encrypt/node_modules/readable-stream/lib/_stream_readable.js`: Module does not exist in the module map`

I believe events module is missing in **package.json**

**Comment by mcollina** [comment]
The events module is provided by Node.js or your bundler. Which bundler are you using? You might need to configure it accordingly.
