### ISSUE TITLE
Streams cookbook

### ISSUE THREAD

**Issue by mafintosh** [nodejs/readable-stream#336]
Bunch of examples for writing streams.

A series of examples on how to write different kind of pipelines etc.

**Comment by indexzero** [comment]
Hot take on TOC for this:

- Using `PassThrough`, `through2`, and `"pipe"` events
- Error handling, invoking `callback` and artificial back pressure. (see: https://github.com/winstonjs/winston/pull/1347)
- Implementing `objectMode` streams.

**Comment by mafintosh** [comment]
Thoughts:

* You prob always want to use readable-stream if you are writing a module

Cookbook example. A stream that writes first to a tmp file, then to a normal file.

```js
const stream = require('readable-stream')

const fd = fs.openSync('file.tmp', 'w')
const ws = stream.Writable({
  write: function (data, enc, cb) {
    write(fd, data, cb)
  },
  // using the final method we can make sure the 'finish' event
  // happens *after* the file has been renamed, which makes composition
  // a lot easier.
  final: function (cb) {
    fs.close(fd, function (err) {
      if (err) return cb(err)
      fs.rename('file.tmp', 'file', cb)
    })
  }
})

function write (data, cb) {
  fs.write(fd, data, 0, data.length, function (err, wrote) {
    if (err) return cb(err)
    data = data.slice(wrote)
    if (data.length) write(data, cb)
    else cb()
  })
}
```

I think the cookbook should just be a bunch of those

**Comment by mafintosh** [comment]
Another example:

```js
const duplexify = require('duplexify')
const http = require('http')

function request (opts) {
  const stream = duplexify()
  const req = http.request(opts, function (res) {
    stream.setReadable(res)
  })
  stream.setWritable(req)
  return stream
}
```

**Comment by mcollina** [comment]
cc @amiller-gh - this is the guide we have been talking about.

**Comment by amiller-gh** [comment]
👍 @add1sun has kicked off the documentation location/format discussion here: https://github.com/nodejs/community-committee/issues/329

Like we talked about at the conf, we don't have *any* technical plans laid out yet for how to store, ingest, and display docs that live alongside – so this is the perfect time to kick off the conversation!

This shouldn't stop you from writing content though. Feel free to start creating more detailed guides for streams in this repo and we can re-format as needed once the website architecture is fleshed out. If we go the in-repo, multiple-source route, it would be great to have `readable-stream` as a guinea pig for the new ingestion pipeline 🙂
