### ISSUE TITLE
Add "Further Reading" section to Streams documentation

### ISSUE THREAD

**Issue by indexzero** [nodejs/readable-stream#337]
As discussed at the Node.js Collaborator summit in Berlin 2018, this new documentation section would cover commonly used modules in the ecosystem to help new folks to node get up to speed on things like:

- `mississippi`
- `end-of-stream` (aka `Stream.finish`)
- `pump` (aka `Stream.pipeline`)
- `through2`
- `duplexify`
- `JSONStream`

**Comment by mcollina** [comment]
cc @amiller-gh
