### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by benhalverson** [nodejs/readable-stream#349]
Hi @mcollina 
We spoke yesterday at Node Summit. I'm interested in being a contributor.

**Comment by mcollina** [comment]
If you would like to help, https://github.com/nodejs/readable-stream/issues/336 would be a fantastic start. It would probably end up in https://github.com/nodejs/nodejs.org/tree/master/locale/en/docs/guides, but it might be better if it came as a PR to this repo.
