### ISSUE TITLE
Move to Buffer.from()

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/readable-stream#358]
`new Buffer(...)` is being used in [a bunch of places](https://github.com/nodejs/readable-stream/search?p=2&q=%22new+Buffer%22&unscoped_q=%22new+Buffer%22) even though it's deprecated. Can we move to `Buffer.from(...)` in those places?

**Comment by mcollina** [comment]
Those are just browsers tests. So, yes we __should__ move to `Buffer.from()` and it's not even a semver-minor change. Would you like to send a PR?

**Comment by gabrielschulhof** [comment]
Can do.

**Comment by gabrielschulhof** [comment]
I guess this landed in 32c1045 so it can be closed, right?
