### ISSUE TITLE
Add a browser polyfill for `process.emitWarning`

### ISSUE THREAD

**Issue by mcollina** [nodejs/readable-stream#361]
> In the browser process.emitWarning is undefined (not a function)

From @jimmywarting

https://github.com/nodejs/readable-stream/commit/e9cde33830a2ee06311f4a7b03d0656720301e4b#r30408314

**Comment by jimmywarting** [comment]
https://github.com/defunctzombie/node-process/issues/83
https://github.com/defunctzombie/node-process/pull/84

**Comment by mcollina** [comment]
Would you like to send a PR?

**Comment by jimmywarting** [comment]
sure
