### ISSUE TITLE
Symbol is undefined in IE11

### ISSUE THREAD

**Issue by jhiesey** [nodejs/readable-stream#364]
In IE11, I get
```
SCRIPT5009: 'Symbol' is undefined
```

The error is coming from https://github.com/nodejs/readable-stream/blob/bbc3ddcc6dcab2c2f7b9db7aaad22d9c979e2a56/lib/_stream_readable.js#L944

**Comment by mcollina** [comment]
Thanks for reporting this. Would you have time to send a PR for this?

**Comment by jhiesey** [comment]
@mcollina would you say the appropriate solution would be to feature test Symbol and just not define asyncIterator if it's not available?

**Comment by mafintosh** [comment]
Yea that sounds like a good approach to me

**Comment by jhiesey** [comment]
OK, so once that's fixed there's a second issue here: https://github.com/nodejs/readable-stream/blob/e890201f99f448c97d3d0bab36c403d8d3f30407/lib/_stream_readable.js#L357

**Comment by jhiesey** [comment]
Thanks!
