### ISSUE TITLE
Number.isNaN() in IE11

### ISSUE THREAD

**Issue by jhiesey** [nodejs/readable-stream#368]
I recently submitted a PR to replace `Number.isNaN(n)` in IE11. It looks like it got moved to a build step, which should be fine.

However, when I require `readable-stream` using browserify, I still get the unreplaced version, which still fails in IE11.

What do I need to do so that when I `require('readable-stream')` I get a version that actually works? Where is the build process supposed to be run, anyway?

**Comment by jhiesey** [comment]
I've been holding off releasing a new major version of `stream-http` until I get this fixed. Should I just go back to `readable-stream` 2 for now?

**Comment by vweevers** [comment]
I think the replacement doesn't take because its regular expression doesn't escape parentheses:

https://github.com/nodejs/readable-stream/blob/9a0365f0cf85b4b203ca3b8fc3d79acf8ed9961e/build/files.js#L196

**Comment by jhiesey** [comment]
Looks like maybe I'm doing something wrong, since your browser tests work. Thoughts?

**Comment by jhiesey** [comment]
Let me try with escaping the parens.

**Comment by mcollina** [comment]
Here is the PR: https://github.com/nodejs/readable-stream/pull/369.

**Comment by mcollina** [comment]
This should be ok, please check.

**Comment by jhiesey** [comment]
Yup that fixes it! Thanks!

**Comment by jhiesey** [comment]
Ah now I see how the build process works. Thanks for the quick fix :)
