### ISSUE TITLE
Delete doc/wg-meeting folder and files

### ISSUE THREAD

**Issue by emlama** [nodejs/readable-stream#386]
Hey, I just did a search for "agenda" on my laptop and found all of these files. Apparently readable-stream is implemented everywhere and is pulled down into all of my node_modules folders.

Really just a nit but fascinating how this got replicated so much!
![screenshot 2018-11-07 13 57 33](https://user-images.githubusercontent.com/30073/48153857-3b6ffe80-e295-11e8-8b15-5e074532a596.png)

**Comment by mcollina** [comment]
Can you please tell me which module versions these belongs to? I’ll release
a patch release on that line. Those are gone in the latest ones.

Il giorno mer 7 nov 2018 alle 18:58 Matthew Saforrian <
notifications@github.com> ha scritto:
