### ISSUE TITLE
npm ci doesn't work with Version 3.1.1. and Angular 7

### ISSUE THREAD

**Issue by Werot1989** [nodejs/readable-stream#397]
Hi everybody,

i upgraded my project from Angular 4.x to Angular 7.
Under Angular 4.x my project works fine with readable-stream 3.1.1. under Angular 7 i get the following message:

npm ERR! enoent ENOENT: no such file or directory, open ..\node_modules\htmlparser2\node_modules\readable-stream\package.json.

It not only appears under the htmlparser2 package, it happens in winston 3.2.1. too, they both use the 3.1.1. Version of readable-stream.

When i change the readable-stream Version to 3.1.0 or lower in the package-lock.json then npm ci works perfectly.

In addition: npm install and  build both working fine with Version 3.1.1. The problem only appears at npm ci

**Comment by mcollina** [comment]
I would recommend to contact npm support, as package resolution is done inside npm itself, and not this module.
