### ISSUE TITLE
^3.1.1 missing finished, pipeline when READABLE_STREAM env var is 'disable'

### ISSUE THREAD

**Issue by trxcllnt** [nodejs/readable-stream#398]
@mcollina We're running into the same issue as https://github.com/fastify/fastify/issues/1413 after updating to fastify rc.6. Looking closer, it seems the main readable-stream ^3.x export is missing the new `finished` and `pipeline` methods when running with `READABLE_STREAM=disable`:
https://github.com/nodejs/readable-stream/blob/1df8b0cf67af5c3f154d37d88085f4b9385a4738/readable.js#L2-L11

Unsetting READABLE_STREAM isn't an option since many dependencies are stuck on readable-stream <= 3.x, and we need the consistency of using node-core streams across the board. I'm able to fix this (for now) by doing an `Object.assign(require('readable-stream'), require('stream'))` before requiring fastify, but this may not be a stable solution as more libraries update to readable-stream 3.x.

**Comment by mcollina** [comment]
I would not recommend running with READABLE_STREAM=disable in production, but you are right, this is a bug. Would you like to send a PR?

**Comment by trxcllnt** [comment]
I'd be happy to, is the `Object.assign()` approach ok with you?

> I would not recommend running with READABLE_STREAM=disable in production

I understand the risk of readable-stream shiping features (and other libs rely on those features) before they land in node core, but that's an acceptable risk considering the alternative is a maelstrom of incompatible `readable-stream` versions (e.g. flowing/non-flowing, no `Symbol.asyncIterator` etc.).

I'm curious, do you know other reasons to not recommend node's built-in streams in production.

**Comment by qm3ster** [comment]
I too, remain curious!
