### ISSUE TITLE
How to read entire stream into buffer

### ISSUE THREAD

**Issue by bajtos** [nodejs/readable-stream#403]
What is the recommended/idiomatic way for reading all data from a stream and store it in a buffer? Preferably using async/await style.

Example:

```ts
const response = await httpGetAsync('http://example.com/');
const body = /* how to read all data into a buffer? */


function httpGetAsync(urlString) {
  return new Promise((resolve, reject) => {
    http.get(urlString, resolve).once('error', reject);
  });
}
```

There are many userland modules in npm (e.g. [get-stream](https://www.npmjs.com/package/get-stream) and [bl](https://www.npmjs.com/package/bl)). The official example in [Node.js docs ](https://nodejs.org/api/http.html#http_http_get_url_options_callback) is using `.on('data')` and `.on('end')` callbacks.

It would be great to have a built-in/native way for converting a readable stream into a buffer ✌️

**Comment by mcollina** [comment]
I totally agree. I persnally use https://www.npmjs.com/package/concat-stream.
Do you see having something like that in core?

**Comment by bajtos** [comment]
> Do you see having something like that in core?

I would love to! But does it have any chance of being accepted? My main concern is about the "small core" argument.

**Comment by mcollina** [comment]
I don't know really. Considering that async iterators will be out of experimental in 12, I would recommend the following:

```js
const chunks = []
for await (let chunk of readable) {
  chunks.push(chunk)
}
console.log(Buffer.concat(chunks))
```

**Comment by bajtos** [comment]
>  Considering that async iterators will be out of experimental in 12, I would recommend the following

That will not work on Node.js 8.x, will it? In our project, we need to support Node.js 8.x for as long as it's supported under the LTS policy (December 2019 at the time of writing).

Would it make sense to add a new utility method, e.g. `stream.readToBuffer(stream, cb)`? I am thinking along the lines of [stream.finished](https://nodejs.org/api/stream.html#stream_stream_finished_stream_options_callback) and [stream.pipeline](https://nodejs.org/api/stream.html#stream_stream_pipeline_streams_callback) APIs.

**Comment by mcollina** [comment]
> That will not work on Node.js 8.x, will it? In our project, we need to support Node.js 8.x for as long as it's supported under the LTS policy (December 2019 at the time of writing).

Yes.

I will just use concat-stream until then, it's well maintained.

**Comment by smitdesai1010** [comment]
You can do it using Fetch in Nodejs. Found the answer on [here](https://stackoverflow.com/questions/14269233/node-js-how-to-read-a-stream-into-a-buffer)
`fetch('https://assets-cdn.github.com/images/modules/logos_page/Octocat.png')
    .then(res => res.buffer())
    .then(buffer => console.log)`
