### ISSUE TITLE
readable-browser.js does not export everything readable.js does

### ISSUE THREAD

**Issue by angelo-v** [nodejs/readable-stream#408]
I am wondering, why `readable-browser.js` is missing some exports. E.g. `readable.js` is exporting `finished` and a library that I am using imports it. `readable-browser.js` does not export finished. Now my application breaks, because `finished` is undefined in a browser application.

Is this intentional? Am I using it wrong?

**Comment by angelo-v** [comment]
`finished` and `pipeline` got added to `readable.js` in [this commit](https://github.com/nodejs/readable-stream/commit/74193c5acd78e17bac61b785ff32c0903833cd16#diff-ab6bca17203019541ae18ae63a2604d3) and it seams to me, that it just was forgotten to update `readable-browser.js`

**Comment by mcollina** [comment]
Good spot! Would you like to send a PR?

**Comment by angelo-v** [comment]
I could add those exports to readable-browser.js, yes. But what is the purpose to differ between `readable-browser.js` and `readable.js` in general? Is the separation still justified?

**Comment by mcollina** [comment]
`readable.js` accesses the `process.env` object. `readable-browser.js` does not, and it will yield smaller bundles.
Overall, yes, they are justified and needed.

**Comment by angelo-v** [comment]
Ok, I will prepare a PR

**Comment by angelo-v** [comment]
fixed via https://github.com/nodejs/readable-stream/pull/409
