### ISSUE TITLE
Adding Readable.from according to node v12.3.0?

### ISSUE THREAD

**Issue by imcotton** [nodejs/readable-stream#411]
Should [Readable.from\(iterable, [options]\)](https://nodejs.org/dist/latest-v12.x/docs/api/stream.html#stream_readable_from_iterable_options) (PR nodejs/node#27660) be picked into here?

**Comment by mcollina** [comment]
This is currently a mirror of Node 10, as a result It will be picked up when it gets backported to Node 10.

**Comment by imcotton** [comment]
I see, thanks for clarify.
