### ISSUE TITLE
node_modules/@types/readable-stream/index.d.ts(138,18): error TS2749: 'StringDecoder' refers to a value, but is being used as a type here.

### ISSUE THREAD

**Issue by REPTILEHAUS** [nodejs/readable-stream#427]
getting this error in an ionic app 

`node_modules/@types/readable-stream/index.d.ts(138,18): error TS2749: 'StringDecoder' refers to a value, but is being used as a type here.`

``` node -v
v10.16.0```

**Comment by mcollina** [comment]
This library does not ship its own types. Open this issue against the `@types/readable-stream` repo.
