### ISSUE TITLE
How to apply to IE11

### ISSUE THREAD

**Issue by luluyes** [nodejs/readable-stream#432]
Hi

The IE11 browser keeps reporting error on "var { Transform } = require('readable-stream');". It says something like it cannot regconize "{". Please tell me how can I fix this. 

Thanks a lot in advance!
Lulu

**Comment by vweevers** [comment]
That syntax ([destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)) isn't supported by IE. Instead do:

```js
var Transform = require('readable-stream').Transform
```

**Comment by luluyes** [comment]
It works! Thank you very much!
