### ISSUE TITLE
Q&A: Why does enabling ES Modules breaks tests?

### ISSUE THREAD

**Issue by Soremwar** [nodejs/readable-stream#433]
The following test `test-stream-pipe-without-listenerCount` breaks when es-modules are enabled on tap.

However the expected behavior seems to only apply when this configuration is enabled, since `listenerCount` is disabled here

![image](https://user-images.githubusercontent.com/42647963/79634429-daa65000-812f-11ea-9722-1f0f4f8c5068.png)

The test fails claiming `listenerCount` is not a function, which is obviously true, _**except**_ when disabling es-modules on the tests. Which seems ilogical.

Is this caused by strict mode? How can it be overwritten to allow its usage with import/export?

**Comment by mcollina** [comment]
I would recommend to open an issue on the `esm` module. It's definitely a compatibility problem on their side.
