### ISSUE TITLE
Error compiling on VS-Studio 2019

### ISSUE THREAD

**Issue by epasinetti** [nodejs/readable-stream#434]
I'm trying to compile a small project with just 2 node modules ... 

const opcua = require("node-opcua");
const sql = require('mssql');

I got this error : 
Error	TS2749	(TS) 'StringDecoder' refers to a value, but is being used as a type here.

**Comment by mcollina** [comment]
I don't really know what is the problem. This module is JavaScript and do not need a compilation step.
