### ISSUE TITLE
Can't use async generators and functions in pipeline

### ISSUE THREAD

**Issue by Sceat** [nodejs/readable-stream#436]
```js
pipeline(
  async function*() { yield 0 },
  async source => {},
  error => { console.log(error) }
)
```
The above is failing with a
```bash
TypeError: stream.on is not a function
```

**Comment by ronag** [comment]
This is not supported in `readable-stream` yet. Please use node v14 and core streams (i.e. `require('stream')`).

**Comment by Sceat** [comment]
Well i'd like to adapt a lib for browser usage so i can't, I'll try to PR this

**Comment by mcollina** [comment]
We'll start working on a v14-based version soon.
