### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by Sceat** [nodejs/readable-stream#437]
Just cloned the repository and saw that dependencies were outdated, is there a specific reason ?

![image](https://user-images.githubusercontent.com/11330271/81010913-5229ee00-8e57-11ea-8bf6-7030d1311c69.png)
![image](https://user-images.githubusercontent.com/11330271/81011058-95845c80-8e57-11ea-9d9e-5b27e4582cea.png)

**Comment by mcollina** [comment]
You are violating our code of conduct and I highly recommend you to amend your issue, thanks.

**Comment by Sceat** [comment]
@mcollina edited to remove my borderline sense of humor :grin:

**Comment by mcollina** [comment]
There are quite a few, mostly because readable-stream v3 still runs on old Node.js releases (v6).

None of those are vulnerability that affect this project or the ability to maintain it, so essentially that cound is useless.
