### ISSUE TITLE
Use the shared travis config with auto-updates for node releases

### ISSUE THREAD

**Issue by dominykas** [nodejs/readable-stream#442]
tl;dr: I'd like to open a PR to replace the `node_js` section in the `.travis.yml` with an imported https://github.com/nodejs/ci-config-travis/blob/master/lts/gte-6.yml

Background: [Package Maintenance WG](https://github.com/nodejs/package-maintenance) has built a repository of [shared Travis CI imports](https://github.com/nodejs/ci-config-travis). The imports will be automatically updated as new Node.js versions get released.

Judging by what's inside the current `.travis.yml` here what's inside `engines`, I suspect that the `lts` upgrade policy is the right fit (it adds new versions as soon as they are released, never removes LTS versions, removes non-LTS versions when they reach EOL)? Or should it be `all` (to take the strict interpretation of what's inside `engines`)?

Is that OK?

**Comment by mcollina** [comment]
lts is the right fit
