### ISSUE TITLE
webpack 5 issue: buffer fallback import crashes webpack compilation

### ISSUE THREAD

**Issue by devkral** [nodejs/readable-stream#448]
Without fallback entry (require("buffer") or false) I get with webpack 5 the error:

ERROR in ./node_modules/safe-buffer/index.js 3:13-30
Module not found: Error: Can't resolve 'buffer' in '/.../node_modules/safe-buffer'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }'
	- install 'buffer'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "buffer": false }
 @ ./node_modules/string_decoder/lib/string_decoder.js 26:13-42
 @ ./node_modules/readable-stream/lib/_stream_readable.js 163:40-80 325:38-78
 @ ./node_modules/readable-stream/readable-browser.js 1:10-63

It would be nice if the import could be rewritten to not crash the webpack compilation.

**Comment by mcollina** [comment]
I think might be better added to https://www.npmjs.com/package/safe-buffer.

**Comment by mcollina** [comment]
cc @feross

**Comment by feross** [comment]
We need Node.js to continue using the built-in buffer which is provided by `require('buffer')` so I can't simple change that require to `require('buffer/')` without a massive performance hit.

One possible solution: Leave the `require('buffer')` as-is but add https://www.npmjs.com/package/buffer as a dependency of `safe-buffer` so that webpack will find it.

Can someone confirm if this approach works? If so, happy to apply the fix.

**Comment by jimmywarting** [comment]
should just stop depending on safe-buffer and switch to using buffer directly instead.

**Comment by mcollina** [comment]
Will be fixed in v4.0.0

**Comment by jaxoncreed** [comment]
I might be missing something, but I'm still having problems with v4.0.0. On a clean install using `react-create-app` (it uses webpack v5), I get the following errors:

```
ERROR in ./node_modules/readable-stream/lib/internal/streams/duplexify.js 5:21-38

Module not found: Error: Can't resolve 'buffer' in '/Users/jackson/O/scratch/test-ldo-react/node_modules/readable-stream/lib/internal/streams'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }'
	- install 'buffer'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "buffer": false }


ERROR in ./node_modules/readable-stream/lib/ours/util.js 3:21-38

Module not found: Error: Can't resolve 'buffer' in '/Users/jackson/O/scratch/test-ldo-react/node_modules/readable-stream/lib/ours'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }'
	- install 'buffer'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "buffer": false }


ERROR in ./node_modules/string_decoder/node_modules/safe-buffer/index.js 4:13-30

Module not found: Error: Can't resolve 'buffer' in '/Users/jackson/O/scratch/test-ldo-react/node_modules/string_decoder/node_modules/safe-buffer'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "buffer": require.resolve("buffer/") }'
	- install 'buffer'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "buffer": false }
```

It looks like `buffer` is still required in those files:
https://github.com/nodejs/readable-stream/blob/main/lib/internal/streams/duplexify.js#L5
https://github.com/nodejs/readable-stream/blob/main/lib/ours/util.js#L3
https://github.com/feross/safe-buffer/blob/master/index.js#L4

**Comment by mcollina** [comment]
Have you followed the docs in https://github.com/nodejs/readable-stream#usage-in-browsers? Could you open a fresh issue in case?
