### ISSUE TITLE
Not able to read all data using stream.read() under 'readable' event.

### ISSUE THREAD

**Issue by ronak-zymr** [nodejs/readable-stream#453]
Hello,

We are using file upload tool to upload multipart data to the server, where we want to parse some request information in between and then unshift the information back to HTTP request.

For that we are using readable event of stream readable class like below:

 ```
httpReq.on('readable', function onReadable() {
      let chunk;
      chunk = httpReq.read();
      while (null !== chunk) {
        if (data !== null) {
          data += chunk.toString();
        } else {
          data = chunk.toString();
        }
        let i=0;
        chunk = httpReq.read();
      }
      if(data === null)
        data = "";
        else {
          const buf = Buffer.from(data, 'utf8');
          data= buf;
        }
     
      // Remove the 'readable' listener before unshifting.
      httpReq.removeListener('readable', onReadable);
      if (data !== null) {
        const buf = Buffer.from(data, 'utf8');
        httpReq.unshift(buf);
       } else {
        data = '';
      }
```

This code works when we have data of less then equal 16KB, but when data exceeds 16KB we are not able to read all the data till EOF and we finish with only 16KB data, because of that we got following error:

```
Error: Unexpected end of multipart data
    at /home/ronak.p@ah.zymrinc.com/projects/iae/iae-nodejs/node_modules/dicer/lib/Dicer.js:61:28
    at process._tickCallback (internal/process/next_tick.js:61:11)
```
Then after i google this issue and came across this [link](https://stackoverflow.com/questions/41478192/nodejs-readable-read-return-null)

I tried using this solution but again it stops after reading 64KB data.

So what should be the correct solution for that ?

Any help will be much appreciated.

Thanks in advancce
Ronak Pandya

**Comment by mcollina** [comment]
It's really hard to help without a full example, could you add one? (a repo is also good).
