### ISSUE TITLE
 Rename default branch from "master" to "main"

### ISSUE THREAD

**Issue by mhdawson** [nodejs/readable-stream#461]
We are going through all of the node.js repositories to rename the primary branch to main. Please see nodejs/node#33864 for more context.

The only references I see in the repo to master (other than in links to licence files which should redirect on their own) are:

```
/README.md

![Node.js](https://github.com/nodejs/readable-stream/workflows/Node.js/badge.svg?branch=master)
![Sauce Labs](https://github.com/nodejs/readable-stream/workflows/Sauce%20Labs/badge.svg?branch=master)
```

@mcollina is this update something you could so?

**Comment by mhdawson** [comment]
ping @mcollina

**Comment by mcollina** [comment]
I’m currently a bit short on time, so if you or anybody else could do it it would be awesome.

**Comment by mhdawson** [comment]
@mcollina did the rename in the README.md and then rename the branch, closing

**Comment by mcollina** [comment]
thx
