### ISSUE TITLE
browser support: use setTimeout instead of process.nextTick

### ISSUE THREAD

**Issue by ashwinkumar6** [nodejs/readable-stream#480]
## Describe the bug
I'm using the [microphone-stream](https://github.com/microphone-stream/microphone-stream) package which in turn uses this package

Consuming this API from the browser throws the following error

**Error**
``` 
Uncaught ReferenceError: process is not defined
    at maybeReadMore (_stream_readable.js:561:1)
    at addChunk (_stream_readable.js:306:1)
    at readableAddChunk (_stream_readable.js:280:1)
    at Readable.push (_stream_readable.js:241:1)
    at ScriptProcessorNode.recorderProcess (microphone-stream.js:108:1)
```

The error seems to be coming from the stream_readable.js file line561
`process.nextTick(maybeReadMore_, stream, state);`
I believe process.nextTick is a NodeJS specific API and isn't available on the browser. setTimeout should be used instead

## Screenshots
![Screen Shot 2022-07-19 at 2 31 21 PM](https://user-images.githubusercontent.com/22762119/179852108-87e1aee9-1da3-4363-9ffb-98d3aa07fff0.png)
![Screen Shot 2022-07-19 at 2 31 35 PM](https://user-images.githubusercontent.com/22762119/179852122-76daca06-f043-4e13-90ed-56e7521c5534.png)

## Your environment
OS: macOS Monterey (12.3.1)
Node: 16.15.1

#### Version number
`microphone-stream@6.0.1`

#### Is the issue in the browser/Node.js?
Browser

#### Details of the browser/Node.js version
Chrome: 103.0.5060.134

**Comment by mcollina** [comment]
Here are the instructions to tell the transpiler how to deal with process and buffer: https://github.com/nodejs/readable-stream#usage-in-browsers
