### ISSUE TITLE
Question on old strange require string_decoder

### ISSUE THREAD

**Issue by robertsLando** [nodejs/readable-stream#481]
I was having issues using MQTT.js on browser with vite. It was throwing me an error that said he cannot found a module, I have investigated and I discovered this:

https://github.com/nodejs/readable-stream/blob/v3.6.0/lib/_stream_readable.js#L163

Manually changing `'string_decoder/'` to `'string_decoder'` fixed the issue

I know now it is fixed in v4.+ but wondering if that was a typo or it's just a sintax that webpack picks up correctly by stripping suffix `/` or whatelse? 

@mcollina

**Comment by mcollina** [comment]
I would say it's better to use v4 if you want to bundle this. The architecture of bundlers changed significantly and v3 has not been kept up to date.
