### ISSUE TITLE
build npm script seems to be broken

### ISSUE THREAD

**Issue by cjihrig** [nodejs/readable-stream#483]
`npm run build 18.8.0` does not seem to work. It fails with the following message:

```
[INFO] Downloading https://nodejs.org/v18.8.0/node-v18.8.0.tar.gz ...
[INFO] Downloading failed with HTTP code 404.
```

This failure also seems to remove the test files, so subsequent `npm test` runs fail.

Is the `build` script still intended to be used? If so, it seems like `dist/` is missing from the download URL.

**Comment by vweevers** [comment]
> Is the `build` script still intended to be used?

Yes. This is a bug. The old build script did have `/dist`:

https://github.com/nodejs/readable-stream/blob/97fd94f404709542a7d69b271eddfcc34345916e/build/build.js#L25

Needs a fix here:

https://github.com/nodejs/readable-stream/blob/77e0378b1a8a46c42fc3fce43969b83abf69ca36/build/build.mjs#L138

**Comment by cjihrig** [comment]
Opened https://github.com/nodejs/readable-stream/pull/484
