### ISSUE TITLE
Problems caused by using ES2021（lib/internal/validators.js ）

### ISSUE THREAD

**Issue by Martin-CF** [nodejs/readable-stream#492]
reason：  Our project uses coap, and then coap depends on readable-stream.
Found after searching： lib/internal/validators.js  use ES2021 causes our project to fail to run normally。
 line-140  const max = 4_294_967_295， It is suggested to change it to  const max = 4294967295

**Comment by tony-go** [comment]
Hey @Martin-CF 👋 

Thanks for reporting this issue.

Could you please provide us with a reproducible example? (like a gist)

**Comment by tony-go** [comment]
Maybe duplicate of https://github.com/nodejs/readable-stream/pull/491/files ?

**Comment by Martin-CF** [comment]
https://github.com/nodejs/readable-stream/blob/main/lib/internal/validators.js
Line 140,   const max = 4_294_967_295
