### ISSUE TITLE
Today I used [patch-package](https://github.com/ds300/patch-package) to patch `readable-stream@3.6.0` for the project I'm working on.

### ISSUE THREAD

**Issue by jingledongding** [nodejs/readable-stream#503]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `readable-stream@3.6.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/readable-stream/lib/internal/streams/stream-browser.js b/node_modules/readable-stream/lib/internal/streams/stream-browser.js
index 9332a3f..dd024fc 100644
--- a/node_modules/readable-stream/lib/internal/streams/stream-browser.js
+++ b/node_modules/readable-stream/lib/internal/streams/stream-browser.js
@@ -1 +1 @@
-module.exports = require('events').EventEmitter;
+module.exports = require('react-native-events').EventEmitter;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by mcollina** [comment]
What should we do about this?

**Comment by benjamingr** [comment]
You should keep your local patch if you want to ussse react-native-events' EventEmitter.

This doesn't belong in readable-stream itself.
