### ISSUE TITLE
Error that I don't know how to fix

### ISSUE THREAD

**Issue by jack11e** [nodejs/readable-stream#504]
It keeps saying this:
Error: Cannot find module 'C:\Program Files\nodejs\node_modules\npm\node_modules\are-we-there-yet\node_modules\readable-stream\lib\ours\index.js'. Please verify that the package.json has a valid "main" entry

**Comment by RishabhKodes** [comment]
Hi @jack11e, I had a similar issue.

Try: 
1. delete your `node_modules` file
2. run `npm i` or `npm install` again

You should be good to go!

**Comment by cullsin** [comment]
Hi, 

I, too, have the same problem. I am using `yarn install`. I have tried multiple node versions. but no improvement. Please suggest. It is occurring for the mongoose npm module.

Raja K
