### ISSUE TITLE
Breaking change in 3.6.1

### ISSUE THREAD

**Issue by jfstephe** [nodejs/readable-stream#505]
Hi,

We are currently using jspm in our project (hoping to move away at some point), but as of today have started getting errors in our builds related to this v3.6.1 of this project. The error is:

  Error: Identifier 'Buffer' has already been declared
    Evaluating jspm_packages/npm/readable-stream@3.6.1/lib/_stream_readable.js
    Evaluating jspm_packages/npm/readable-stream@3.6.1/readable-browser.js

I can't offer much more information other than the above.

Other dependencies are bringing this in, and I was wondering if you could either un-publish it, or re-publish 3.6.0 as 3.6.2 and then publish this as a major change update?

John

**Comment by mcollina** [comment]
Thanks for reporting! This is definitely unwanted.

Can you provide steps to reproduce? We often need a [reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), e.g. some code that allows someone else to recreate your problem by just copying and pasting it. If it involves more than a couple of different file, create a new repository on GitHub and add a link to that.

**Comment by jfstephe** [comment]
Thanks for the quick response.

I completely understand re: reproducible example. TBH it's going to take be a reasonable amount of effort for me to create that and jspm is old tech now anyway...

I've resolved my issue by changing the dependencies of the third party dependencies that use readable-stream using the following in the jspm overrides section of my package.json:
```

      "npm:hash-base@3.1.0": {
        "dependencies": {
          "inherits": "2.0.4",
          "readable-stream": "3.6.0",
          "safe-buffer": "5.2.1"
        }
      },
      "npm:browserify-sign@4.2.1": {
        "dependencies": {
          "inherits": "2.0.4",
          "readable-stream": "3.6.0",
          "safe-buffer": "5.2.1",
          "create-hash": "1.2.0",
          "create-hmac": "1.1.7",
          "browserify-rsa": "4.1.0",
          "parse-asn1": "5.1.6",
          "elliptic": "6.5.4",
          "bn.js": "5.2.1"
        }

```

If this isn't hurting anyone else then perhaps we just accept it. At least this will hopefully serve as assistance if anyone else has the problem!

**Comment by mcollina** [comment]
This should not have caused any regression. I'm sorry it did but I would really like to know why so it can be fixed.
