### ISSUE TITLE
v4 npm release?

### ISSUE THREAD

**Issue by SourceBoy** [nodejs/readable-stream#510]
Hi, is there a roadmap for the v4 release? We have a need to use the latest `stream.Readable.fromWeb` and `toWeb` to convert the 2 different implementations of streams.

Use case: Web stream -> Node stream -> Processing -> Web stream

**Comment by SourceBoy** [comment]
So they won't exist in v4 either? Will they be brought back if/once the ones from Node core is no longer experimental?

**Comment by mcollina** [comment]
It really requires someone to drive the work for supporting those outside of core. Ideally we want to support the native implementation of WHATWG Streams on every platform.

**Comment by SourceBoy** [comment]
Thanks. For anyone looking to convert the 2 different streams bidirectionally, here's a function-based implementation: https://gist.github.com/SourceBoy/e45d94e58589f4652cafa4f4ae1c3dd6
