### ISSUE TITLE
v4.5.0: global is not defined

### ISSUE THREAD

**Issue by mofux** [nodejs/readable-stream#529]
I just upgraded to readable-stream@4.5.0 and I am now getting this error (using readable-stream in the browser):

`global is not defined`

I tracked these changes back to [this commit](https://github.com/nodejs/readable-stream/commit/4c8e8e528b46b9dba6cd4385b2f8195214dcc682#diff-9b8bb809feb796e3edeadfc9bc0cc24ced47a83b6be73d2fb9d95c868e54d75dR5), where there are many references to `global` that did not exist before. I'm wondering if they should be changed to `globalThis` instead, so it will not crash in browsers (`global` is only globally defined in node).

Here is one of the affected places for quick reference:
https://github.com/nodejs/readable-stream/blob/700d28b674a440ee939d0d88491e9040c45de642/lib/ours/util.js#L5-L6

**Comment by mcollina** [comment]
I could only track those two places.

**Comment by mofux** [comment]
There is another occurence in `src/util.js`. Not sure if it also needs to be changed.

https://github.com/nodejs/readable-stream/blob/700d28b674a440ee939d0d88491e9040c45de642/src/util.js#L5-L6

**Comment by mofux** [comment]
Thanks for the quick fix and maintaining this package ❤️  I can confirm that my problem is fixed now 🎉
