### ISSUE TITLE
@types/readable-stream says not to use Duplex.from

### ISSUE THREAD

**Issue by 10xLaCroixDrinker** [nodejs/readable-stream#534]
When Node 12.5 was released, `Duplex.from` was marked deprecated in @types/readable-stream, with the note "This is a dummy function required to retain type compatibility to node." This doesn't seem to be the case anymore. Can we remove the deprecated tag?

[@types/readable-stream/index.d.ts#L279-L284](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1a4e1c0367022020b2825ef28839a76e33a66f5a/types/readable-stream/index.d.ts#L279-L284)
```ts
    class Duplex extends _Writable implements _IDuplex, /*extends*/ _Readable, Duplex {
        /**
         * This is a dummy function required to retain type compatibility to node.
         * @deprecated DO NOT USE
         */
        static from(source: any): any;
```

**Comment by mcollina** [comment]
You'll need to send a PR to definitelytyped, those types are not part of the nodejs project
