### ISSUE TITLE
Library resolves to Node.js '`string_decoder`' module in Vercel Edge Environment

### ISSUE THREAD

**Issue by jeswr** [nodejs/readable-stream#547]
When trying to use the `Readable` exported by this library in a Vercel Edge Function one gets the following error:

```
Error during transformationError: The edge runtime does not support Node.js 'string_decoder' module.
```

**Comment by jeswr** [comment]
Thanks for merging @MattiasBuelens - would appreciate if this patch could be released sooner rather than later.

Also, happy New Year 🥳

**Comment by MattiasBuelens** [comment]
I don't think I have the powers necessary to publish a new release. 😅 I'll let @mcollina do the honors.
