### ISSUE TITLE
Running tests in the browser

### ISSUE THREAD

**Issue by feross** [nodejs/readable-stream#86]
I've been trying to get the `readable-stream` tests to pass in the browser in hopes that this module can become the default `stream` implementation in browserify. But it's way trickier than I expected!

I've been working on this on and off over the last two months, but I keep quitting because it's so frustrating. I'll share my progress in the hopes that someone can come up with a better approach and take it from here.

Issues:

**Some tests don't make sense in the browser.** They use `fs`, etc. Solution: skip these tests. Easy.

**The tests don't use a test runner designed for the browser like `tape`.** When you you browserify all the tests (`tests/browser/*.js`) they run simultaneously leading to super confusing/incorrect output. Possible solution: Wrap each test file with a giant tape `test` block so tape can run the tests sequentially. Replace all the `assert` calls with equivalent `t.*` calls. Make all `console.log`s and `console.error`s into no-ops so the embedded `console.log('ok')` calls don't interfere. Did this on my fork and it seemed to work alright. Except for...

**Nearly all tests use `setTimeout`, `setInterval`, `process.nextTick`, and `process.on('exit')`** to delay writing data into streams for some time, or to assert some final conditions about the various streams on exit. `process.on('exit')` makes no sense in the browser, so perhaps we can turn these into a no-op. Still, we're left with the main problem: how do we tell when all the `setTimeout`s and `setInterval`s are finished we can end the test with `t.end()`? In node, this is tracked internally and `process.on('exit')` is emitted when there's nothing left in the event queue.

First I tried changing all the `process.on('exit', fn)` calls to `setTimeout(fn, 5000)` and it actually worked (on my own machine), though it made the tests take like 5 minutes to run. The problem is that this won't work on remote CI services like testling where the performance of the machines can vary wildly. Sometimes 5000 was not enough. When I tried increasing it more, the tests would get killed for taking to long to complete. :( This is so hacky and gross anyway...

Then I tried emulating the node behavior of `setTimeout` and `setInterval` in the browser, and emitting `process.on('exit')` when there are no timers left. I wrote [timers-ref](https://github.com/feross/timers-ref) which exports timer functions that have as node-like behavior as possible. Seems to mostly work alright, though some tests are still failing. I haven't added `process.nextTick` support yet and I bet that's why they're failing. I don't know enough about `process.nextTick` to add that in yet. And I'm also concerned that hacks to emulate it won't have the exact correct behavior cross-browser anyway, which would negate the whole point of making these tests work in the browser. And this still feels fragile and hacky.

I think perhaps the best solution is to rewrite the tests from scratch, but that sounds like a lot of work. And this whole experience has already been so frustrating.

**Comment by calvinmetcalf** [comment]
and we do run tests in the browser
