### ISSUE TITLE
Browserifiability

### ISSUE THREAD

**Issue by rvagg** [nodejs/readable-stream#88]
@substack @calvinmetcalf @feross @maxogden

I've merged all the PRs and synchronised the build scripts between the master and v0.10 branches--this was causing major pain in getting everything merged so I wouldn't be surprised if some things didn't go in properly.

Could you each check over both the master and v0.10 branches and see if they're doing what you wanted to be done for browserifiability for both 1.1 and 1.0 releases of readable-stream?

**Comment by AutoSponge** [comment]
I've noticed, while using jspm, that the browserified version of 1.13 fails to import.  I traced it to this line:

https://github.com/iojs/readable-stream/blob/3b672fd7ae92acf5b4ffdbabf74b372a0a56b051/lib/_stream_readable.js#L54

which translates to:
```
var debug = require('@empty');
```

After changing the file to:
```
var debug = require('util');
```

Everything works as expected.  I'm guessing that `util` is not in the deps list and jspm can't map it.  Is this something to fix here or in browserify or jspm?

**Comment by calvinmetcalf** [comment]
util was not supposed to be imported, its set to false in the package.json, likely an jspm issue would be my guess

**Comment by sonewman** [comment]
@AutoSponge if you required `util` that would include more than the debug, also in the code where it calles `debug(*something*)` wouldn't that throw `TypeError: object is not a function`?

**Comment by AutoSponge** [comment]
@sonewman I think we have the fix for this in SystemJS now.  It will guard against this case by injecting an `@empty` module (ref above).

**Comment by calvinmetcalf** [comment]
closing this as it is browserifiable and if other build systems have issues we can open up issues for those
