### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by leetreveil** [nodejs/readable-stream#89]
With node 0.8.26 and npm 1.2.30 `npm install readable-stream` is broken.

``` bash
npm ERR! Error: No compatible version found: inherits@'^2.0.1'
npm ERR! Valid install targets:
npm ERR! ["1.0.0","2.0.0","2.0.1"]
npm ERR!     at installTargetsError (/Users/leetreveil/.nvm/v0.8.26/lib/node_modules/npm/lib/cache.js:726:10)
npm ERR!     at /Users/leetreveil/.nvm/v0.8.26/lib/node_modules/npm/lib/cache.js:648:10
npm ERR!     at saved (/Users/leetreveil/.nvm/v0.8.26/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:141:7)
npm ERR!     at Object.oncomplete (fs.js:297:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Darwin 13.1.0
npm ERR! command "/Users/leetreveil/.nvm/v0.8.26/bin/node" "/Users/leetreveil/.nvm/v0.8.26/bin/npm" "install" "readable-stream"
npm ERR! cwd /Users/leetreveil/.npm
npm ERR! node -v v0.8.26
npm ERR! npm -v 1.2.30
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/leetreveil/.npm/npm-debug.log
npm ERR! not ok code 0
```

**Comment by naveenbirru** [comment]
I am seeing this error. is it related ?

{ [Error: No compatible version found: readable-stream@'>=2.0.0 <2.1.0'
Valid install targets:
["0.0.1","0.0.2","0.0.3","0.0.4","0.1.0","0.2.0","0.3.0","0.3.1","1.0.0","1.0.1","1.0.2","1.0.15","1.0.17","1.1.7","1.1.8","1.1.9","1.0.24","1.0.25","1.1.10","1.0.25-1","1.1.11","1.0.26","1.0.26-1","1.1.11-1","1.0.26-2","1.1.12","1.0.26-3","1.0.26-4","1.1.12-1","1.0.27-1","1.1.13-1","1.0.31","1.1.13","1.0.32","1.0.32-1","1.0.33-1","1.0.33-2","1.0.33"]
17-Jun-2015 17:49:27 	] code: 'ETARGET', parent: 'concat-stream' }

**Comment by calvinmetcalf** [comment]
Can you run 'npm cache clean' and then try reinstalling?
